
# 3.19 :RECord Commands

["3.19.1 :RECord:WRECord:ENABle"]
Syntax = ":RECord:WRECord:ENABle <bool> :RECord:WRECord:ENABle?"
Description = "Enables or disables the waveform recording function; or queries the on/off status of the waveform recording function."
Remarks = "N/A"
Return_Format = "The query returns 0 or 1."
Example = ":RECord:WRECord:ENABle ON    /*Enables waveform recording.*/ :RECord:WRECord:ENABle?    /*Returns 1.*/"
Class = "Record.Waveform"
Function = "enable"
Command = ":RECord:WRECord:ENABle"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "Boolean"
Is_Query = "True"

["3.19.2 :RECord:ENABle"]
Syntax = ":RECord:ENABle <bool> :RECord:ENABle?"
Description = "Enables or disables the waveform recording function (backwards compatibility); or queries the on/off status."
Remarks = "Use :RECord:WRECord:ENABle instead."
Return_Format = "The query returns 0 or 1."
Example = ":RECord:ENABle ON    /*Enables waveform recording.*/ :RECord:ENABle?    /*Returns 1.*/"
Class = "Record"
Function = "enable"
Command = ":RECord:ENABle"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "Boolean"
Is_Query = "True"

["3.19.3 :RECord:WRECord:OPERate"]
Syntax = ":RECord:WRECord:OPERate <operate> :RECord:WRECord:OPERate?"
Description = "Starts or stops waveform recording; or queries whether recording is running."
Remarks = "N/A"
Return_Format = "The query returns RUN or STOP."
Example = ":RECord:WRECord:OPERate RUN    /*Starts recording.*/ :RECord:WRECord:OPERate?    /*Returns RUN.*/"
Class = "Record.Waveform"
Function = "operate"
Command = ":RECord:WRECord:OPERate"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{RUN|STOP}"
Is_Query = "True"

["3.19.4 :RECord:STARt"]
Syntax = ":RECord:STARt <bool> :RECord:STARt?"
Description = "Starts waveform recording (backwards compatibility); or queries whether recording is active."
Remarks = "Use :RECord:WRECord:OPERate instead."
Return_Format = "The query returns 1 or 0."
Example = ":RECord:STARt ON    /*Starts recording.*/ :RECord:STARt?    /*Returns 1.*/"
Class = "Record"
Function = "start"
Command = ":RECord:STARt"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "Boolean"
Is_Query = "True"

["3.19.5 :RECord:WRECord:FRAMes"]
Syntax = ":RECord:WRECord:FRAMes <value> :RECord:WRECord:FRAMes?"
Description = "Sets or queries the number of frames for waveform recording."
Remarks = "N/A"
Return_Format = "The query returns an integer between 1 and the maximum recordable frames."
Example = ":RECord:WRECord:FRAMes 300    /*Records 300 frames.*/ :RECord:WRECord:FRAMes?    /*Returns 300.*/"
Class = "Record.Waveform"
Function = "frames"
Command = ":RECord:WRECord:FRAMes"
Input_Min = "1"
Input_Max = "MaxFrames"
Input_Values = "Integer"
Is_Query = "True"

["3.19.6 :RECord:FRAMes"]
Syntax = ":RECord:FRAMes <value> :RECord:FRAMes?"
Description = "Sets or queries the number of frames for waveform recording (backwards compatibility)."
Remarks = "Use :RECord:WRECord:FRAMes instead."
Return_Format = "The query returns an integer."
Example = ":RECord:FRAMes 300    /*Records 300 frames.*/ :RECord:FRAMes?    /*Returns 300.*/"
Class = "Record"
Function = "frames"
Command = ":RECord:FRAMes"
Input_Min = "1"
Input_Max = "MaxFrames"
Input_Values = "Integer"
Is_Query = "True"

["3.19.7 :RECord:WRECord:FRAMes:MAX"]
Syntax = ":RECord:WRECord:FRAMes:MAX"
Description = "Sets the number of recorded frames to the maximum recordable frames."
Remarks = "N/A"
Return_Format = "N/A"
Example = ":RECord:WRECord:FRAMes:MAX    /*Sets maximum recordable frames.*/"
Class = "Record.Waveform"
Function = "max_frames"
Command = ":RECord:WRECord:FRAMes:MAX"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "False"

["3.19.8 :RECord:WRECord:FMAX?"]
Syntax = ":RECord:WRECord:FMAX?"
Description = "Queries the maximum number of frames that can be recorded currently."
Remarks = "N/A"
Return_Format = "The query returns an integer (max recordable frames based on current memory depth)."
Example = "N/A"
Class = "Record.Waveform"
Function = "max_frames_query"
Command = ":RECord:WRECord:FMAX?"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "True"

["3.19.9 :RECord:WRECord:FINTerval"]
Syntax = ":RECord:WRECord:FINTerval <interval> :RECord:WRECord:FINTerval?"
Description = "Sets or queries the time interval between frames in waveform recording."
Remarks = "N/A"
Return_Format = "The query returns the interval in scientific notation (s)."
Example = ":RECord:WRECord:FINTerval 1    /*Sets interval to 1 s.*/ :RECord:WRECord:FINTerval?    /*Returns 1.000000E0.*/"
Class = "Record.Waveform"
Function = "frame_interval"
Command = ":RECord:WRECord:FINTerval"
Input_Min = "1e-12"
Input_Max = "10"
Input_Values = "Float"
Is_Query = "True"

["3.19.10 :RECord:WRECord:PROMpt"]
Syntax = ":RECord:WRECord:PROMpt <bool> :RECord:WRECord:PROMpt?"
Description = "Sets or queries the beeper status when recording is completed."
Remarks = "N/A"
Return_Format = "The query returns 0 or 1."
Example = ":RECord:WRECord:PROMpt ON    /*Enables beeper on completion.*/ :RECord:WRECord:PROMpt?    /*Returns 1.*/"
Class = "Record.Waveform"
Function = "prompt"
Command = ":RECord:WRECord:PROMpt"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "Boolean"
Is_Query = "True"

["3.19.11 :RECord:WREPlay:FCURrent"]
Syntax = ":RECord:WREPlay:FCURrent <value> :RECord:WREPlay:FCURrent?"
Description = "Sets or queries the current frame in waveform playback."
Remarks = "N/A"
Return_Format = "The query returns an integer."
Example = ":RECord:WREPlay:FCURrent 300    /*Sets current playback frame to 300.*/ :RECord:WREPlay:FCURrent?    /*Returns 300.*/"
Class = "Record.Waveform.Replay"
Function = "current_frame"
Command = ":RECord:WREPlay:FCURrent"
Input_Min = "1"
Input_Max = "MaxFrames"
Input_Values = "Integer"
Is_Query = "True"

["3.19.12 :RECord:CURRent"]
Syntax = ":RECord:CURRent <value> :RECord:CURRent?"
Description = "Sets or queries the current frame in waveform playback (backwards compatibility)."
Remarks = "Use :RECord:WREPlay:FCURrent instead."
Return_Format = "The query returns an integer."
Example = ":RECord:CURRent 300    /*Sets current frame to 300.*/ :RECord:CURRent?    /*Returns 300.*/"
Class = "Record"
Function = "current_frame"
Command = ":RECord:CURRent"
Input_Min = "1"
Input_Max = "MaxFrames"
Input_Values = "Integer"
Is_Query = "True"

["3.19.13 :RECord:WREPlay:FCURrent:TIME?"]
Syntax = ":RECord:WREPlay:FCURrent:TIME?"
Description = "Queries the timestamp of the current frame in waveform playback."
Remarks = "N/A"
Return_Format = "The query returns the timestamp as a string."
Example = "N/A"
Class = "Record.Waveform.Replay"
Function = "current_frame_time"
Command = ":RECord:WREPlay:FCURrent:TIME?"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "True"

["3.19.14 :RECord:WREPlay:FSTart"]
Syntax = ":RECord:WREPlay:FSTart <start> :RECord:WREPlay:FSTart?"
Description = "Sets or queries the start frame for waveform playback."
Remarks = "N/A"
Return_Format = "The query returns the start frame as an integer."
Example = ":RECord:WREPlay:FSTart 10    /*Sets start frame to 10.*/ :RECord:WREPlay:FSTart?    /*Returns 10.*/"
Class = "Record.Waveform.Replay"
Function = "start_frame"
Command = ":RECord:WREPlay:FSTart"
Input_Min = "1"
Input_Max = "MaxFrames"
Input_Values = "Integer"
Is_Query = "True"

["3.19.15 :RECord:WREPlay:FEND"]
Syntax = ":RECord:WREPlay:FEND <end> :RECord:WREPlay:FEND?"
Description = "Sets or queries the end frame for waveform playback."
Remarks = "N/A"
Return_Format = "The query returns the end frame as an integer."
Example = ":RECord:WREPlay:FEND 346    /*Sets end frame to 346.*/ :RECord:WREPlay:FEND?    /*Returns 346.*/"
Class = "Record.Waveform.Replay"
Function = "end_frame"
Command = ":RECord:WREPlay:FEND"
Input_Min = "1"
Input_Max = "MaxFrames"
Input_Values = "Integer"
Is_Query = "True"

["3.19.16 :RECord:WREPlay:FMAX?"]
Syntax = ":RECord:WREPlay:FMAX?"
Description = "Queries the maximum number of frames that can be played back currently."
Remarks = "N/A"
Return_Format = "The query returns an integer representing the maximum playable frames."
Example = "N/A"
Class = "Record.Waveform.Replay"
Function = "max_playback_frames"
Command = ":RECord:WREPlay:FMAX?"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "True"

["3.19.17 :RECord:WREPlay:FINTerval"]
Syntax = ":RECord:WREPlay:FINTerval <interval> :RECord:WREPlay:FINTerval?"
Description = "Sets or queries the time interval between frames in waveform playback."
Remarks = "N/A"
Return_Format = "The query returns the interval in scientific notation (s)."
Example = ":RECord:WREPlay:FINTerval 1    /*Sets interval to 1 s.*/ :RECord:WREPlay:FINTerval?    /*Returns 1.000000E0.*/"
Class = "Record.Waveform.Replay"
Function = "playback_frame_interval"
Command = ":RECord:WREPlay:FINTerval"
Input_Min = "1e-3"
Input_Max = "1"
Input_Values = "Float"
Is_Query = "True"

["3.19.18 :RECord:WREPlay:MODE"]
Syntax = ":RECord:WREPlay:MODE <mode> :RECord:WREPlay:MODE?"
Description = "Sets the waveform playback mode to Repeat or Single; or queries the playback mode."
Remarks = "N/A"
Return_Format = "The query returns REP or SING."
Example = ":RECord:WREPlay:MODE REP    /*Sets playback mode to REP.*/ :RECord:WREPlay:MODE?    /*Returns REP.*/"
Class = "Record.Waveform.Replay"
Function = "mode"
Command = ":RECord:WREPlay:MODE"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{REP|SING}"
Is_Query = "True"

["3.19.19 :RECord:WREPlay:DIRection"]
Syntax = ":RECord:WREPlay:DIRection <direction> :RECord:WREPlay:DIRection?"
Description = "Sets the playback direction in waveform playback; or queries the direction."
Remarks = "N/A"
Return_Format = "The query returns FORW or BACK."
Example = ":RECord:WREPlay:DIRection BACK    /*Sets direction to BACK.*/ :RECord:WREPlay:DIRection?    /*Returns BACK.*/"
Class = "Record.Waveform.Replay"
Function = "direction"
Command = ":RECord:WREPlay:DIRection"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{FORW|BACK}"
Is_Query = "True"

["3.19.20 :RECord:WREPlay:OPERate"]
Syntax = ":RECord:WREPlay:OPERate <operate> :RECord:WREPlay:OPERate?"
Description = "Enables or disables waveform playback; or queries the playback status."
Remarks = "N/A"
Return_Format = "The query returns RUN or STOP."
Example = ":RECord:WREPlay:OPERate RUN    /*Starts playback.*/ :RECord:WREPlay:OPERate?    /*Returns RUN.*/"
Class = "Record.Waveform.Replay"
Function = "operate"
Command = ":RECord:WREPlay:OPERate"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{RUN|STOP}"
Is_Query = "True"

["3.19.21 :RECord:PLAY"]
Syntax = ":RECord:PLAY <bool> :RECord:PLAY?"
Description = "Enables or disables waveform playback (backwards compatibility); or queries the playback status."
Remarks = "Use :RECord:WREPlay:OPERate instead."
Return_Format = "The query returns 1 or 0."
Example = ":RECord:PLAY ON    /*Starts playback.*/ :RECord:PLAY?    /*Returns 1.*/"
Class = "Record.Waveform.Replay"
Function = "play"
Command = ":RECord:PLAY"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "Boolean"
Is_Query = "True"

["3.19.22 :RECord:WREPlay:BACK"]
Syntax = ":RECord:WREPlay:BACK"
Description = "Plays back the previous frame manually."
Remarks = "N/A"
Return_Format = "N/A"
Example = ":RECord:WREPlay:BACK    /*Plays previous frame.*/"
Class = "Record.Waveform.Replay"
Function = "play_previous_frame"
Command = ":RECord:WREPlay:BACK"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "False"

["3.19.23 :RECord:WREPlay:NEXT"]
Syntax = ":RECord:WREPlay:NEXT"
Description = "Plays back the next frame manually."
Remarks = "N/A"
Return_Format = "N/A"
Example = ":RECord:WREPlay:NEXT    /*Plays next frame.*/"
Class = "Record.Waveform.Replay"
Function = "play_next_frame"
Command = ":RECord:WREPlay:NEXT"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "False"

["3.19.24 :RECord:WREPlay:PLAY"]
Syntax = ":RECord:WREPlay:PLAY <val> :REFerence:SOURce <ref>,<chan> :REFerence:SOURce? <ref>"
Description = "Starts playback from a specified frame position and sets or queries the reference channel source."
Remarks = "• FFIRst: starts from the first frame. • FEND: starts from the last frame. Only enabled channels may be used as reference sources. D0-D15 are available only on the DHO900 series."
Return_Format = "N/A"
Example = ":RECord:WREPlay:PLAY FEND    /*Starts playback from the last frame.*/"
Class = "Record.Waveform.Replay"
Function = "play_from_frame"
Command = ":RECord:WREPlay:PLAY"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{FFIRst|FEND}"
Is_Query = "False"


["3.19.1 :RECord:WRECord:ENABle".Parameter]
Name = "<bool>"
Type = "Bool"
Default = "0|OFF"
Range = "{{1|ON}|{0|OFF}}"

["3.19.2 :RECord:ENABle".Parameter]
Name = "<bool>"
Type = "Bool"
Default = "0|OFF"
Range = "{{1|ON}|{0|OFF}}"

["3.19.3 :RECord:WRECord:OPERate".Parameter]
Name = "<operate>"
Type = "Discrete"
Default = "STOP"
Range = "{RUN|STOP}"

["3.19.4 :RECord:STARt".Parameter]
Name = "<bool>"
Type = "Bool"
Default = "0|OFF"
Range = "{{1|ON}|{0|OFF}}"

["3.19.5 :RECord:WRECord:FRAMes".Parameter]
Name = "<value>"
Type = "Integer"
Default = "1,000"
Range = "1 to the maximum number of frames that can be recorded currently"

["3.19.6 :RECord:FRAMes".Parameter]
Name = "<value>"
Type = "Integer"
Default = "219"
Range = "1 to the maximum number of frames that can be recorded currently 1,000"

["3.19.7 :RECord:WRECord:FRAMes:MAX".Parameter]
Info = "N/A"

["3.19.8 :RECord:WRECord: FMAX?".Parameter]
Info = "Data incomplete or malformed"

["3.19.9 :RECord:WRECord:FINTerval".Parameter]
Name = "<interval>"
Type = "Real"
Default = "ns"
Range = "10 ns to 1 s 10"

["3.19.10 :RECord:WRECord:PROMpt".Parameter]
Name = "<bool>"
Type = "Bool"
Default = "1|ON"
Range = "{{1|ON}|{0|OFF}}"

["3.19.11 :RECord:WREPlay:FCURrent".Parameter]
Name = "<value>"
Type = "Integer"
Default = "recorded"
Range = "1 to the maximum number of frames recorded The maximum number of frames"

["3.19.12 :RECord:CURRent".Parameter]
Name = "<value>"
Type = "Integer"
Default = "recorded"
Range = "1 to the maximum number of frames recorded The maximum number of frames"

["3.19.13 :RECord:WREPlay:FCURrent:TIME?".Parameter]
Info = "N/A"

["3.19.14 :RECord:WREPlay:FSTart".Parameter]
Name = "<start>"
Type = "Integer"
Default = "-"
Range = "1 to the maximum number of frames that can be played back currently"

["3.19.15 :RECord:WREPlay:FEND".Parameter]
Name = "<end>"
Type = "Integer"
Default = "-"
Range = "1 to the maximum number of frames recorded"

["3.19.16 :RECord:WREPlay:FMAX?".Parameter]
Info = "N/A"

["3.19.17 :RECord:WREPlay:FINTerval".Parameter]
Name = "<interval>"
Type = "Real"
Default = "-"
Range = "1 ms to 1 s"

["3.19.18 :RECord:WREPlay:MODE".Parameter]
Name = "<mode>"
Type = "Discrete"
Default = "SINGle"
Range = "{REPeat|SINGle}"

["3.19.19 :RECord:WREPlay:DIRection".Parameter]
Name = "<direction>"
Type = "Discrete"
Default = "FORWard"
Range = "{FORWard|BACKward}"

["3.19.20 :RECord:WREPlay:OPERate".Parameter]
Name = "<operate>"
Type = "Discrete"
Default = "STOP"
Range = "{RUN|STOP}"

["3.19.21 :RECord:PLAY".Parameter]
Name = "<bool>"
Type = "Bool"
Default = "0|OFF"
Range = "{{1|ON}|{0|OFF}}"

["3.19.22 :RECord:WREPlay:BACK".Parameter]
Info = "Data incomplete or malformed"

["3.19.23 :RECord:WREPlay:NEXT".Parameter]
Info = "N/A"

["3.19.24 :RECord:WREPlay:PLAY".Parameter]
Name = "<val>"
Type = "Discrete"
Default = "CHANnel1"
Range = "{FFIRst|FEND} FFIRst 229 Name Type Range Default <ref> Discrete {1|2|3|4|5|6|7|8|9|10} - <chan> Discrete {D0|D1|D2|D3|D4|D5|D6|D7|D8| D9|D10|D11|D12|D13|D14|D15| CHANnel1|CHANnel2| CHANnel3|CHANnel4|MATH1| MATH2|MATH3|MATH4}"
