# 3.22 :SEARch Commands

["3.22.1 :SEARch:COUNt?"]
Syntax = ":SEARch:COUNt?"
Description = "Queries the total number of the search events."
Remarks = "N/A"
"Return Format" = "The query returns the total number of the search events in integer."
Example = "N/A"
Class = "Search"
Function = "count"
Command = ":SEARch:COUNt?"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "Yes"

["3.22.2 :SEARch:STATe"]
Syntax = ":SEARch:STATe <bool> :SEARch:STATe?"
Description = "Enables or disables the search function; or queries the on/off status of the search function."
Remarks = "N/A"
"Return Format" = "The query returns 1 or 0."
Example = ":SEARch:STATe ON    /*Enables the search function.*/ :SEARch:STATe?      /*The query returns 1.*/"
Class = "Search"
Function = "state"
Command = ":SEARch:STATe"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "Boolean"
Is_Query = "Yes"

["3.22.3 :SEARch:MODE"]
Syntax = ":SEARch:MODE <value> :SEARch:MODE?"
Description = "Sets the search type."
Remarks = "• EDGe: selects \"Edge\" as the search type. • PULSe: selects \"Pulse\" as the search type."
"Return Format" = "The query returns EDGE or PULS."
Example = ":SEARch:MODE PULSe    /*Selects the search type to \"PULSe\".*/ :SEARch:MODE?         /*The query returns PULS.*/"
Class = "Search"
Function = "mode"
Command = ":SEARch:MODE"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{EDGE|PULSe}"
Is_Query = "Yes"

["3.22.4 :SEARch:EVENt"]
Syntax = ":SEARch:EVENt <value> :SEARch:EVENt?"
Description = "Sets to navigate a search event."
Remarks = "N/A"
"Return Format" = "The query returns an integer."
Example = ":SEARch:EVENt 1    /*Sets to navigate to Search Event 1.*/ :SEARch:EVENt?      /*The query returns 1.*/"
Class = "Search"
Function = "event"
Command = ":SEARch:EVENt"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "Integer"
Is_Query = "Yes"

["3.22.5 :SEARch:VALue?"]
Syntax = ":SEARch:VALue? <x>"
Description = "Queries the time value for the specified Line No. in the marktable."
Remarks = "<x> denotes the line number of the marktable."
"Return Format" = "The query returns a time value."
Example = "N/A"
Class = "Search"
Function = "value"
Command = ":SEARch:VALue?"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "Yes"

["3.22.6 :SEARch:EDGE:SLOPe"]
Syntax = ":SEARch:EDGE:SLOPe <slope> :SEARch:EDGE:SLOPe?"
Description = "Sets or queries the edge for the \"Edge\" search type."
Remarks = "• POSitive: rising edge. • NEGative: falling edge. • EITHer: either rising or falling edge."
"Return Format" = "The query returns POS, NEG, or EITH."
Example = ":SEARch:EDGE:SLOPe NEGative    /*Sets the edge type to NEGative.*/ :SEARch:EDGE:SLOPe?            /*The query returns NEG.*/"
Class = "Search.Edge"
Function = "slope"
Command = ":SEARch:EDGE:SLOPe"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{POSitive|NEGative|EITHer}"
Is_Query = "Yes"

["3.22.7 :SEARch:EDGE:SOURce"]
Syntax = ":SEARch:EDGE:SOURce <source> :SEARch:EDGE:SOURce?"
Description = "Sets or queries the source for the \"Edge\" search type."
Remarks = "N/A"
"Return Format" = "The query returns CHAN1, CHAN2, CHAN3, or CHAN4."
Example = ":SEARch:EDGE:SOURce CHANnel1    /*Sets the source for the Edge search type to CHANnel1.*/ :SEARch:EDGE:SOURce?            /*The query returns CHAN1.*/"
Class = "Search.Edge"
Function = "source"
Command = ":SEARch:EDGE:SOURce"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{CHANnel1|CHANnel2|CHANnel3|CHANnel4}"
Is_Query = "Yes"

["3.22.8 :SEARch:EDGE:THReshold"]
Syntax = ":SEARch:EDGE:THReshold <thre> :SEARch:EDGE:THReshold?"
Description = "Sets or queries the threshold for the \"Edge\" search type."
Remarks = "N/A"
"Return Format" = "The query returns the threshold in scientific notation."
Example = ":SEARch:EDGE:THReshold 0.01         /*Sets the threshold to 0.01 V.*/ :SEARch:EDGE:THReshold?           /*The query returns 1.000000E-2.*/"
Class = "Search.Edge"
Function = "threshold"
Command = ":SEARch:EDGE:THReshold"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "float"
Is_Query = "Yes"

["3.22.9 :SEARch:PULSe:POLarity"]
Syntax = ":SEARch:PULSe:POLarity <polarity> :SEARch:PULSe:POLarity?"
Description = "Sets or queries the polarity for the \"Pulse\" search type."
Remarks = "N/A"
"Return Format" = "The query returns POS or NEG."
Example = ":SEARch:PULSe:POLarity POSitive    /*Sets the polarity for the Pulse search type to POSitive.*/ :SEARch:PULSe:POLarity?           /*The query returns POS.*/"
Class = "Search.Pulse"
Function = "polarity"
Command = ":SEARch:PULSe:POLarity"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{POSitive|NEGative}"
Is_Query = "Yes"

["3.22.10 :SEARch:PULSe:QUALifier"]
Syntax = ":SEARch:PULSe:QUALifier <qualifier> :SEARch:PULSe:QUALifier?"
Description = "Sets or queries the search condition for the \"Pulse\" search type."
Remarks = "• GREater: pulse width > specified width. • LESS: pulse width < specified width. • GLESs: pulse width between specified limits."
"Return Format" = "The query returns GRE, LESS, or GLES."
Example = ":SEARch:PULSe:QUALifier LESS    /*Sets the search condition for \"Pulse\" to LESS.*/ :SEARch:PULSe:QUALifier?           /*The query returns LESS.*/"
Class = "Search.Pulse"
Function = "qualifier"
Command = ":SEARch:PULSe:QUALifier"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{GREater|LESS|GLESs}"
Is_Query = "Yes"

["3.22.11 :SEARch:PULSe:SOURce"]
Syntax = ":SEARch:PULSe:SOURce <source> :SEARch:PULSe:SOURce?"
Description = "Sets or queries the source for the \"Pulse\" search type."
Remarks = "N/A"
"Return Format" = "The query returns CHAN1, CHAN2, CHAN3, or CHAN4."
Example = ":SEARch:PULSe:SOURce CHANnel1    /*Sets the source for the Pulse search type to CHANnel1.*/ :SEARch:PULSe:SOURce?            /*The query returns CHAN1.*/"
Class = "Search.Pulse"
Function = "source"
Command = ":SEARch:PULSe:SOURce"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{CHANnel1|CHANnel2|CHANnel3|CHANnel4}"
Is_Query = "Yes"

["3.22.12 :SEARch:PULSe:UWIDth"]
Syntax = ":SEARch:PULSe:UWIDth <width> :SEARch:PULSe:UWIDth?"
Description = "Sets or queries the upper limit of the pulse width for the \"Pulse\" search type."
Remarks = "N/A"
"Return Format" = "The query returns the upper limit of the pulse width in scientific notation."
Example = ":SEARch:PULSe:UWIDth 1   /*Sets the upper limit of the pulse width for the Pulse search type to 1 s.*/ :SEARch:PULSe:UWIDth?           /*The query returns 1.000000E0.*/"
Class = "Search.Pulse"
Function = "upper_width"
Command = ":SEARch:PULSe:UWIDth"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "float"
Is_Query = "Yes"

["3.22.13 :SEARch:PULSe:LWIDth"]
Syntax = ":SEARch:PULSe:LWIDth <width> :SEARch:PULSe:LWIDth?"
Description = "Sets or queries the lower limit of the pulse width for the \"Pulse\" search type."
Remarks = "N/A"
"Return Format" = "The query returns the lower limit of the pulse width in scientific notation."
Example = ":SEARch:PULSe:LWIDth 0.2   /*Sets the lower limit of the pulse width to 200 ms.*/ :SEARch:PULSe:LWIDth?           /*The query returns 2.000000E-1.*/"
Class = "Search.Pulse"
Function = "lower_width"
Command = ":SEARch:PULSe:LWIDth"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "float"
Is_Query = "Yes"

["3.22.14 :SEARch:PULSe:THReshold"]
Syntax = ":SEARch:PULSe:THReshold <thre> :SEARch:PULSe:THReshold? :NAVigate:ENABle <bool> :NAVigate:ENABle? :NAVigate:MODE <mode> :NAVigate:MODE?"
Description = "Sets or queries the threshold for the \"Pulse\" search type. Sets or queries the on/off status of the Navigation function. Sets or queries the navigation mode."
Remarks = "N/A N/A • TIME: indicates time navigation (available only in \"YT\" mode)."
"Return Format" = "• The query returns the threshold in scientific notation. • The query returns 1 or 0."
Example = ":SEARch:PULSe:THReshold 0.01         /*Sets the threshold to 10 mV.*/ :SEARch:PULSe:THReshold?           /*The query returns 1.000000E-2.*/"
Class = "Search.Pulse"
Function = "threshold"
Command = ":SEARch:PULSe:THReshold"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "float"
Is_Query = "Yes"


# --- Parameter Blocks (already provided above, kept for completeness) ---

["3.22.1 :SEARch:COUNt?".Parameter]
Info = "N/A"

["3.22.2 :SEARch:STATe".Parameter]
Name = "<bool>"
Type = "Bool"
Default = "0|OFF"
Range = "{{1|ON}|{0|OFF}}"

["3.22.3 :SEARch:MODE".Parameter]
Name = "<value>"
Type = "Discrete"
Default = "245"
Range = "{EDGE|PULSe} EDGE"

["3.22.4 :SEARch:EVENt".Parameter]
Name = "<value>"
Type = "Integer"
Default = "0"
Range = "0 to (the number of searched events – 1)"

["3.22.5 :SEARch:VALue?".Parameter]
Name = "<x>"
Type = "Integer"
Default = "-"
Range = "-"

["3.22.6 :SEARch:EDGE:SLOPe".Parameter]
Name = "<slope>"
Type = "Discrete"
Default = "POSitive"
Range = "{POSitive|NEGative|EITHer}"

["3.22.7 :SEARch:EDGE:SOURce".Parameter]
Name = "<source>"
Type = "Discrete"
Default = "CHANnel1"
Range = "{CHANnel1|CHANnel2| CHANnel3|CHANnel4}"

["3.22.8 :SEARch:EDGE:THReshold".Parameter]
Name = "<thre>"
Type = "Real"
Default = "V"
Range = "(-4.5 x VerticalScale - Offset) to (4.5 x VerticalScale - Offset) 0.000"

["3.22.9 :SEARch:PULSe:POLarity".Parameter]
Name = "<polarity>"
Type = "Discrete"
Default = "POSitive"
Range = "{POSitive|NEGative}"

["3.22.10 :SEARch:PULSe:QUALifier".Parameter]
Name = "<qualifier>"
Type = "Discrete"
Default = "GREater"
Range = "{GREater|LESS|GLESs}"

["3.22.11 :SEARch:PULSe:SOURce".Parameter]
Name = "<source>"
Type = "Discrete"
Default = "CHANnel1"
Range = "{CHANnel1|CHANnel2| CHANnel3|CHANnel4}"

["3.22.12 :SEARch:PULSe:UWIDth".Parameter]
Name = "<width>"
Type = "Real"
Default = "us"
Range = "800 ps to 10 s 2"

["3.22.13 :SEARch:PULSe:LWIDth".Parameter]
Name = "<width>"
Type = "Real"
Default = "us"
Range = "800 ps to 10 s 1"

["3.22.14 :SEARch:PULSe:THReshold".Parameter]
Name = "<thre>"
Type = "Real"
Default = "TIME"
Range = "(-5 × VerticalScale - OFFSet) to (5 × VerticalScale - OFFSet) 0.000 V Name Type Range Default <bool> Bool {{1|ON}|{0|OFF}} 0|OFF Name Type Range Default <mode> Discrete {TIME|SEARch|FRAMe}"
