# 3.23 :NAVigate Commands

["3.23.1 :NAVigate:ENABle"]
Syntax = ":NAVigate:ENABle <bool> :NAVigate:ENABle?"
Description = "Sets or queries the on/off status of the Navigation function."
Remarks = "N/A"
"Return Format" = "The query returns 1 or 0."
Example = ":NAVigate:ENABle ON    /*Enables the Navigation function.*/ :NAVigate:ENABle?      /*The query returns 1.*/"
Class = "Navigate"
Function = "enable"
Command = ":NAVigate:ENABle"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{OFF|ON}"
Is_Query = "Yes"

["3.23.2 :NAVigate:MODE"]
Syntax = ":NAVigate:MODE <mode> :NAVigate:MODE?"
Description = "Sets or queries the navigation mode."
Remarks = "• TIME: indicates time navigation (available only in \"YT\" time mode). • SEARch: event search navigation. • FRAMe: frame segment navigation. When UltraAcquire is enabled, FRAMe is automatically selected and cannot be modified. The navigation function is available only when the oscilloscope is in STOP state."
"Return Format" = "The query returns TIME, SEARch, or FRAMe."
Example = ":NAVigate:MODE TIME /*Sets the navigation mode to TIME.*/ :NAVigate:MODE? /*The query returns TIME.*/"
Class = "Navigate"
Function = "mode"
Command = ":NAVigate:MODE"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{TIME|SEARch|FRAMe}"
Is_Query = "Yes"

["3.23.3 :NAVigate:TIME:SPEed"]
Syntax = ":NAVigate:TIME:SPEed <speed> :NAVigate:TIME:SPEed?"
Description = "Sets the speed of playing the waveforms in time navigation mode."
Remarks = "• HIGH: plays waveforms at a high speed. • NORMal: at normal speed. • LOW: at low speed."
"Return Format" = "The query returns HIGH, NORMal, or LOW."
Example = ":NAVigate:TIME:SPEed LOW /*Sets the speed to LOW.*/ :NAVigate:TIME:SPEed? /*The query returns LOW.*/"
Class = "Navigate.Time"
Function = "speed"
Command = ":NAVigate:TIME:SPEed"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{HIGH|NORMal|LOW}"
Is_Query = "Yes"

["3.23.4 :NAVigate:TIME:PLAY"]
Syntax = ":NAVigate:TIME:PLAY <bool> :NAVigate:TIME:PLAY?"
Description = "Sets or queries whether to play the waveforms in time navigation mode."
Remarks = "• 1|ON: starts playing the waveforms. • 0|OFF: stops playing the waveforms."
"Return Format" = "The query returns 1 or 0."
Example = ":NAVigate:TIME:PLAY ON /*Starts playing the waveforms in time navigation mode.*/ :NAVigate:TIME:PLAY? /*The query returns 1.*/"
Class = "Navigate.Time"
Function = "play"
Command = ":NAVigate:TIME:PLAY"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{OFF|ON}"
Is_Query = "Yes"

["3.23.5 :NAVigate:TIME:END"]
Syntax = ":NAVigate:TIME:END"
Description = "Sets to navigate to the end waveforms (rightmost end of screen) in time navigation mode."
Remarks = "N/A"
"Return Format" = "N/A"
Example = "N/A"
Class = "Navigate.Time"
Function = "end"
Command = ":NAVigate:TIME:END"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "No"

["3.23.6 :NAVigate:TIME:STARt"]
Syntax = ":NAVigate:TIME:STARt"
Description = "Sets to navigate to the start waveforms (leftmost end of screen) in time navigation mode."
Remarks = "N/A"
"Return Format" = "N/A"
Example = "N/A"
Class = "Navigate.Time"
Function = "start"
Command = ":NAVigate:TIME:STARt"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "No"

["3.23.7 :NAVigate:TIME:NEXT"]
Syntax = ":NAVigate:TIME:NEXT"
Description = "Sets to play forward the waveform in time navigation mode."
Remarks = "N/A"
"Return Format" = "N/A"
Example = "N/A"
Class = "Navigate.Time"
Function = "next"
Command = ":NAVigate:TIME:NEXT"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "No"

["3.23.8 :NAVigate:TIME:BACK"]
Syntax = ":NAVigate:TIME:BACK"
Description = "Sets to play backward the waveform in time navigation mode."
Remarks = "N/A"
"Return Format" = "N/A"
Example = "N/A"
Class = "Navigate.Time"
Function = "back"
Command = ":NAVigate:TIME:BACK"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "No"

["3.23.9 :NAVigate:SEARch:END"]
Syntax = ":NAVigate:SEARch:END"
Description = "Sets to navigate to the last event."
Remarks = "N/A"
"Return Format" = "N/A"
Example = "N/A"
Class = "Navigate.Search"
Function = "end"
Command = ":NAVigate:SEARch:END"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "No"

["3.23.10 :NAVigate:SEARch:STARt"]
Syntax = ":NAVigate:SEARch:STARt"
Description = "Sets to navigate to the first event."
Remarks = "N/A"
"Return Format" = "N/A"
Example = "N/A"
Class = "Navigate.Search"
Function = "start"
Command = ":NAVigate:SEARch:STARt"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "No"

["3.23.11 :NAVigate:SEARch:NEXT"]
Syntax = ":NAVigate:SEARch:NEXT"
Description = "Sets to navigate to the next event."
Remarks = "N/A"
"Return Format" = "N/A"
Example = "N/A"
Class = "Navigate.Search"
Function = "next"
Command = ":NAVigate:SEARch:NEXT"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "No"

["3.23.12 :NAVigate:SEARch:BACK"]
Syntax = ":NAVigate:SEARch:BACK"
Description = "Sets to navigate to the previous event."
Remarks = "N/A"
"Return Format" = "N/A"
Example = "N/A"
Class = "Navigate.Search"
Function = "back"
Command = ":NAVigate:SEARch:BACK"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "No"

["3.23.13 :NAVigate:FRAMe:DISPlay:MODE"]
Syntax = ":NAVigate:FRAMe:DISPlay:MODE <mode> :NAVigate:FRAMe:DISPlay:MODE?"
Description = "Sets or queries the display mode in Frame Segment navigation."
Remarks = "• ADJacent, OVERlay, WATerfall, PERSpective, MOSaic."
"Return Format" = "The query returns ADJ, OVER, WAT, PERS, or MOS."
Example = ":NAVigate:FRAMe:DISPlay:MODE ADJacent /*Sets to ADJacent mode.*/ :NAVigate:FRAMe:DISPlay:MODE? /*Returns ADJ.*/"
Class = "Navigate.Frame.Display"
Function = "mode"
Command = ":NAVigate:FRAMe:DISPlay:MODE"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{ADJacent|OVERlay|WATerfall|PERSpective|MOSaic}"
Is_Query = "Yes"

["3.23.14 :NAVigate:FRAMe:END:FRAMe"]
Syntax = ":NAVigate:FRAMe:END:FRAMe <frame> :NAVigate:FRAMe:END:FRAMe?"
Description = "Sets or queries the end frame in Frame Segment navigation mode."
Remarks = "The range of the end frame is from Start Frame to the maximum number of frames acquired in UltraAcquire mode."
"Return Format" = "The query returns an integer."
Example = ":NAVigate:FRAMe:END:FRAMe 8 /*Sets End Frame to 8.*/ :NAVigate:FRAMe:END:FRAMe? /*Returns 8.*/"
Class = "Navigate.Frame"
Function = "end_frame"
Command = ":NAVigate:FRAMe:END:FRAMe"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "Integer"
Is_Query = "Yes"

["3.23.15 :NAVigate:FRAMe:STARt:FRAMe"]
Syntax = ":NAVigate:FRAMe:STARt:FRAMe <frame> :NAVigate:FRAMe:STARt:FRAMe?"
Description = "Sets or queries the start frame in Frame Segment navigation."
Remarks = "Playback begins from the specified Start Frame."
"Return Format" = "The query returns an integer."
Example = ":NAVigate:FRAMe:STARt:FRAMe 3 /*Sets Start Frame to 3.*/ :NAVigate:FRAMe:STARt:FRAMe? /*Returns 3.*/"
Class = "Navigate.Frame"
Function = "start_frame"
Command = ":NAVigate:FRAMe:STARt:FRAMe"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "Integer"
Is_Query = "Yes"

["3.23.16 :NAVigate:FRAMe:END"]
Syntax = ":NAVigate:FRAMe:END"
Description = "Sets to play the final page in Frame Segment navigation mode."
Remarks = "N/A"
"Return Format" = "N/A"
Example = "N/A"
Class = "Navigate.Frame"
Function = "end"
Command = ":NAVigate:FRAMe:END"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "No"

["3.23.17 :NAVigate:FRAMe:STARt"]
Syntax = ":NAVigate:FRAMe:STARt"
Description = "Sets to play the first page in Frame Segment navigation mode."
Remarks = "N/A"
"Return Format" = "N/A"
Example = "N/A"
Class = "Navigate.Frame"
Function = "start"
Command = ":NAVigate:FRAMe:STARt"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "No"

["3.23.18 :NAVigate:FRAMe:NEXT"]
Syntax = ":NAVigate:FRAMe:NEXT"
Description = "Sets to play the next page in Frame Segment navigation mode."
Remarks = "N/A"
"Return Format" = "N/A"
Example = "N/A"
Class = "Navigate.Frame"
Function = "next"
Command = ":NAVigate:FRAMe:NEXT"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "No"

["3.23.19 :NAVigate:FRAMe:BACK"]
Syntax = ":NAVigate:FRAMe:BACK"
Description = "Sets to play the previous page in Frame Segment navigation mode."
Remarks = "N/A"
"Return Format" = "N/A"
Example = "N/A"
Class = "Navigate.Frame"
Function = "back"
Command = ":NAVigate:FRAMe:BACK"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "No"

["3.23.20 :NAVigate:FRAMe:PLAY"]
Syntax = ":NAVigate:FRAMe:PLAY <bool> :NAVigate:FRAMe:PLAY? :SYSTem:AOUTput <auxoutput> :SYSTem:AOUTput?"
Description = "Sets or queries whether to play the waveforms in Frame Segment navigation mode. Also shows the syntax for configuring the AUX OUT signal."
Remarks = "• 1|ON: starts playing frames. • 0|OFF: stops playing frames. When playing, Start/End Frame cannot be changed. • TOUT: sets the AUX OUT to output a signal at each trigger."
"Return Format" = "The query returns 1 or 0."
Example = ":NAVigate:FRAMe:PLAY ON /*Starts playing frames.*/ :NAVigate:FRAMe:PLAY? /*Returns 1.*/"
Class = "Navigate.Frame"
Function = "play"
Command = ":NAVigate:FRAMe:PLAY"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "Boolean"
Is_Query = "Yes"

["3.23.1 :NAVigate:ENABle".Parameter]
Name = "<bool>"
Type = "Bool"
Default = "0|OFF"
Range = "{{1|ON}|{0|OFF}}"

["3.23.2 :NAVigate:MODE".Parameter]
Name = "<mode>"
Type = "Discrete"
Default = "TIME"
Range = "{TIME|SEARch|FRAMe}"

["3.23.3 :NAVigate:TIME:SPEed".Parameter]
Name = "<speed>"
Type = "Discrete"
Default = "NORMal"
Range = "{HIGH|NORMal|LOW}"

["3.23.4 :NAVigate:TIME:PLAY".Parameter]
Name = "<bool>"
Type = "Bool"
Default = "0|OFF"
Range = "{{1|ON}|{0|OFF}}"

["3.23.5 :NAVigate:TIME:END".Parameter]
Info = "Data incomplete or malformed"

["3.23.6 :NAVigate:TIME:STARt".Parameter]
Info = "N/A"

["3.23.7 :NAVigate:TIME:NEXT".Parameter]
Info = "N/A"

["3.23.8 :NAVigate:TIME:BACK".Parameter]
Info = "N/A"

["3.23.9 :NAVigate:SEARch:END".Parameter]
Info = "N/A"

["3.23.10 :NAVigate:SEARch:STARt".Parameter]
Info = "N/A"

["3.23.11 :NAVigate:SEARch:NEXT".Parameter]
Info = "N/A"

["3.23.12 :NAVigate:SEARch:BACK".Parameter]
Info = "N/A"

["3.23.13 :NAVigate:FRAMe:DISPlay:MODE".Parameter]
Name = "<mode>"
Type = "Discrete"
Default = "-"
Range = "{ADJacent|OVERlay|WATerfall| PERSpective|MOSaic}"

["3.23.14 :NAVigate:FRAMe:END:FRAMe".Parameter]
Name = "<frame>"
Type = "Integer"
Default = "260"
Range = "- -"

["3.23.15 :NAVigate:FRAMe:STARt:FRAMe".Parameter]
Name = "<frame>"
Type = "Integer"
Default = "-"
Range = "-"

["3.23.16 :NAVigate:FRAMe:END".Parameter]
Info = "N/A"

["3.23.17 :NAVigate:FRAMe:STARt".Parameter]
Info = "N/A"

["3.23.18 :NAVigate:FRAMe:NEXT".Parameter]
Info = "N/A"

["3.23.19 :NAVigate:FRAMe:BACK".Parameter]
Info = "N/A"

["3.23.20 :NAVigate:FRAMe:PLAY".Parameter]
Name = "<bool>"
Type = "Bool"
Default = "TOUT"
Range = "{{1|ON}|{0|OFF}} 0|OFF Name Type Range Default <auxoutput> Discrete {TOUT|PFAil}"
