# 3.24 :SYSTem Commands
["3.24.1 :SYSTem:AOUTput"]
Syntax = ":SYSTem:AOUTput <auxoutput> :SYSTem:AOUTput?"
Description = "Sets or queries the type of the signal output from the rear-panel [AUX OUT] connector."
Remarks = "• TOUT: after you select this type, the oscilloscope initiates a trigger and then a signal which reflects the current capture rate of the oscilloscope can be output from the connector. 264 • PFAil: after you select this type, a pulse signal will be output from the connector once the oscilloscope detects a successful or failed event."
"Return Format" = "The query returns TOUT or PFA."
Example = ":SYSTem:AOUTput PFAil   /*Sets the signal type to PFAil.*/ :SYSTem:AOUTput?      /*The query returns PFA.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.24.2 :SYSTem:BEEPer"]
Syntax = ":SYSTem:BEEPer <bool> :SYSTem:BEEPer?"
Description = "Turns on or off the beeper or queries the on/off status of the beeper."
Remarks = "N/A"
"Return Format" = "The query returns 1 or 0."
Example = ":SYSTem:BEEPer ON    /*Enables the beeper.*/ :SYSTem:BEEPer?      /*The query returns 1.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.24.3 :SYSTem:ERRor[:NEXT]?"]
Syntax = ":SYSTem:ERRor[:NEXT]?"
Description = "Queries and clears the error queue message."
Remarks = "N/A"
"Return Format" = "The query is in <Message Number>,<Message Content> format. Wherein, <Message Number> is an integer; <Message Content> is a double-quoted ASCII string. For example, -113,\"Undefined header; command cannot be found\"."
Example = "N/A"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.24.4 :SYSTem:PON"]
Syntax = ":SYSTem:PON <power_on> :SYSTem:PON?"
Description = "Sets or queries the configuration type recalled by the oscilloscope when it is powered on again after power-off."
Remarks = "N/A"
"Return Format" = "The query returns LAT or DEF."
Example = ":SYSTem:PON LATest        /*Sets the oscilloscope to recall Last value after it is powered on again.*/ :SYSTem:PON?             /*The query returns LAT.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.24.5 :SYSTem:PSTatus"]
Syntax = ":SYSTem:PSTatus <sat> :SYSTem:PSTatus? 266"
Description = "Sets or queries the power status of the oscilloscope."
Remarks = "• DEFault: after the oscilloscope is powered on, you need to press the Power key on the front panel to start the oscilloscope. • OPEN: after the oscilloscope is powered on, it starts directly. You do not have to press the Power key."
"Return Format" = "The query returns DEF or OPEN."
Example = ":SYSTem:PSTatus DEFault        /*Sets the power status to DEFault.*/ :SYSTem:PSTatus?              /*The query returns DEF.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.24.6 :SYSTem:OPTion:INSTall"]
Syntax = ":SYSTem:OPTion:INSTall <license>"
Description = "Installs an option."
Remarks = "• To install the option, first purchase the required option to obtain the key, and then use the key to obtain the option license according to the following steps. - Log in to the RIGOL official website (http://www.rigol.com). Click SERVICE CENTRE (Products & Services) > License Activation to enter the license activation interface. 267 - In the interface, input the correct key, serial number (Click or tap Utility to enter the system utility menu. In the menu, click or tap System > About to obtain the serial number.), and the verification code. Click Generate to obtain the download link of the option license file. If you need to use the option license file, click to download the file to the specified directory of the USB storage device. • The <license> format is \"<series>-<opt>@<code>\". - <series>: indicates the product series. - <opt>: indicates the option name. The options supported include: BODE: bode plot option (only supported by the DHO924S and DHO914S models). - <code>: The license is a fixed length of strings. Each instrument has a unique license."
"Return Format" = "N/A"
Example = ":SYSTem:OPTion:INSTall DHO900- BODE@A7DEC6C1E10D42EE8E3AF0728C3D272F507E646EB54B9C97E6CCBA98468A46A 863FED814C24D47B8B40C894B1822660B94852E6778392281A20B54B4E723E3FD"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.24.7 :SYSTem:OPTion:UNINstall"]
Syntax = ":SYSTem:OPTion:UNINstall"
Description = "Uninstalls all the official options."
Remarks = "After the option has been uninstalled, you need to restart the instrument."
"Return Format" = "N/A 268"
Example = "N/A"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.24.8 :SYSTem:OPTion:STATus?"]
Syntax = ":SYSTem:OPTion:STATus? <type>"
Description = "Queries whether an option is activated or not."
Remarks = "BODE: bode plot option (only supported by the DHO924S and DHO914S models)."
"Return Format" = "The query returns 0 or 1. • 0: indicates that the option is not installed. • 1: indicates that the official option has been installed."
Example = "N/A"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.24.9 :SYSTem:OPTion:VALid?"]
Syntax = ":SYSTem:OPTion:VALid? <type>"
Description = "Queries whether an option is activated or not."
Remarks = "BODE: bode plot option (only supported by the DHO924S and DHO914S models). 269"
"Return Format" = "The query returns 0 or 1. • 0: indicates that the option is not installed. • 1: indicates that the official option has been installed."
Example = "N/A"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.24.10 :SYSTem:RAMount?"]
Syntax = ":SYSTem:RAMount?"
Description = "Queries the number of analog channels of the current instrument."
Remarks = "N/A"
"Return Format" = "The query returns the number of analog channels of the current instrument in integer."
Example = "N/A"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.24.11 :SYSTem:RESet"]
Syntax = ":SYSTem:RESet"
Description = "Resets the system to power on."
Remarks = "N/A 270"
"Return Format" = "N/A"
Example = "N/A"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.24.12 :SYSTem:SETup"]
Syntax = ":SYSTem:SETup <setup_data> :SYSTem:SETup?"
Description = "Sends or reads the data stream of the system setup file."
Remarks = "• <setup_data> is a binary data block, which consists of the TMC data block header and setup data. - The format of the TMC data block header is #NX…X. Wherein, # is the start identifier of the data stream; the N-digit data \"X...X\" (N≤9) following the start identifier indicate the length of the data stream (the number of bytes). For example, 9000002506 Wherein, N is 9, 000002506 following it represents that the data stream contains 2506 bytes of effective data. - The setup data are expressed in ASCII format. • When sending the command, directly place the data stream after the command string, then complete the whole sending process in one time. When reading the data stream, ensure that there is enough buffer space to receive the data stream; otherwise, errors might occur in reading the program."
"Return Format" = "N/A"
Example = "N/A 271"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.24.13 :SYSTem:LOCKed"]
Syntax = ":SYSTem:LOCKed <bool> :SYSTem:LOCKed?"
Description = "Enables or disables the front-panel key operation and touch screen operation; queries whether the front-panel key operation and touch screen operation are locked."
Remarks = "N/A"
"Return Format" = "The query returns 1 or 0."
Example = ":SYSTem:LOCKed ON          /*Disables the front-panel key operation and touch screen operation.*/ :SYSTem:LOCKed?            /*The query returns 1.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.24.14 :SYSTem:MODules?"]
Syntax = ":SYSTem:MODules?"
Description = "Queries the hardware modules."
Remarks = "N/A"
"Return Format" = "The query returns 1,0,0,0,0. The first figure indicates LA; the second figure indicates DG; and the others are not defined currently. 1 indicates available, and 0 indicates not available. 272"
Example = "N/A"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.24.15 :SYSTem:AUToscale"]
Syntax = ":SYSTem:AUToscale <bool> :SYSTem:AUToscale?"
Description = "Enables or disables the function of the Auto menu; or queries the on/off status of the Auto menu."
Remarks = "• You can send this command or use the menu key to disable the function of the AUTO key. • After the function of the AUTO key is disabled, you cannot perform the Auto Scale operation."
"Return Format" = "The query returns 1 or 0."
Example = ":SYSTem:AUToscale ON    /*Enables the function of the front-panel AUTO key.*/ :SYSTem:AUToscale?      /*The query returns 1.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.24.16 :SYSTem:GAMount?"]
Syntax = ":SYSTem:GAMount?"
Description = "Queries the number of grids in the horizontal direction of the screen."
Remarks = "N/A"
"Return Format" = "The query returns the number of grids in integer. For this oscilloscope, the query returns a fixed value 10."
Example = "N/A"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.24.17 :SYSTem:VERSion?"]
Syntax = ":SYSTem:VERSion?"
Description = "Queries the version number of the SCPI used by the system."
Remarks = "N/A"
"Return Format" = "The query returns the SCPI version number in strings."
Example = ":SYSTem:VERSion?   /*The query returns 3.0.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.24.18 :SYSTem:DGSTatus?"]
Syntax = ":SYSTem:DGSTatus?"
Description = "Queries whether the DG module exists."
Remarks = "N/A 274"
"Return Format" = "The query returns 1 or 0."
Example = ":SYSTem:DGSTatus? /*The query returns 1 if the instrument has installed the DG module; otherwise, it returns 0.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.24.19 :SYSTem:KEYBOARDCheck?"]
Syntax = ":SYSTem:KEYBOARDCheck? :SOURce:OUTPut:STATe <bool> :SOURce:OUTPut:STATe? 275"
Description = "Queries the status of the keyboard."
Remarks = "N/A"
"Return Format" = "The query returns true or false."
Example = "N/A 3.25 :SOURce Commands :SOURce commands are used to set AFG parameters. This series oscilloscope has a standard built-in 25 MHz AFG, which integrates the signal source and the oscilloscope into one. NOTE The commands are only available for DHO914S and DHO924S. 3.25.1 :SOURce:OUTPut:STATe"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.24.1 :SYSTem:AOUTput".Parameter]
Name = "<auxoutput>"
Type = "Discrete"
Default = "TOUT"
Range = "{TOUT|PFAil}"

["3.24.2 :SYSTem:BEEPer".Parameter]
Name = "<bool>"
Type = "Bool"
Default = "0|OFF"
Range = "{{1|ON}|{0|OFF}}"

["3.24.3 :SYSTem:ERRor[:NEXT]?".Parameter]
Info = "Data incomplete or malformed"

["3.24.4 :SYSTem:PON".Parameter]
Name = "<power_on>"
Type = "Discrete"
Default = "DEFault"
Range = "{LATest|DEFault}"

["3.24.5 :SYSTem:PSTatus".Parameter]
Name = "<sat>"
Type = "Discrete"
Default = "OPEN"
Range = "{DEFault|OPEN}"

["3.24.6 :SYSTem:OPTion:INSTall".Parameter]
Name = "<license>"
Type = "ASCII"
Default = "-"
Range = "String Refer to Remarks"

["3.24.7 :SYSTem:OPTion:UNINstall".Parameter]
Info = "N/A"

["3.24.8 :SYSTem:OPTion:STATus?".Parameter]
Name = "<type>"
Type = "Discrete"
Default = "-"
Range = "{BODE}"

["3.24.9 :SYSTem:OPTion:VALid?".Parameter]
Name = "<type>"
Type = "Discrete"
Default = "-"
Range = "{BODE}"

["3.24.10 :SYSTem:RAMount?".Parameter]
Info = "N/A"

["3.24.11 :SYSTem:RESet".Parameter]
Info = "N/A"

["3.24.12 :SYSTem:SETup".Parameter]
Name = "<setup_data>"
Type = "Binary"
Default = "-"
Range = "Refer to Remarks"

["3.24.13 :SYSTem:LOCKed".Parameter]
Name = "<bool>"
Type = "Bool"
Default = "0|OFF"
Range = "{{1|ON}|{0|OFF}}"

["3.24.14 :SYSTem:MODules?".Parameter]
Info = "N/A"

["3.24.15 :SYSTem:AUToscale".Parameter]
Name = "<bool>"
Type = "Bool"
Default = "1|ON"
Range = "{{1|ON}|{0|OFF}}"

["3.24.16 :SYSTem:GAMount?".Parameter]
Info = "Data incomplete or malformed"

["3.24.17 :SYSTem:VERSion?".Parameter]
Info = "N/A"

["3.24.18 :SYSTem:DGSTatus?".Parameter]
Info = "N/A"

["3.24.19 :SYSTem:KEYBOARDCheck?".Parameter]
Info = "N/A"
