# 3.25 :SOURce Commands
["3.25.1 :SOURce:OUTPut:STATe"]
Syntax = ":SOURce:OUTPut:STATe <bool> :SOURce:OUTPut:STATe? 275"
Description = "Enables or disables the channel output; or queries the channel output status."
Remarks = "N/A"
"Return Format" = "The query returns 0 or 1. Examples :SOURce:OUTPut:STATe ON /*Enables the channel output for AFG.*/ :SOURce:OUTPut:STATe? /*The query returns 1.*/"
Example = ""
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.25.2 :SOURce:FUNCtion"]
Syntax = ":SOURce:FUNCtion <wave> :SOURce:FUNCtion?"
Description = "Sets or queries the function of the basic waveform."
Remarks = "The built-in Function/Arbitrary Waveform Generator of this series can output a variety of basic waveforms, including Sine, Square, Ramp, DC, Noise, and Arb."
"Return Format" = "The query returns SIN, SQU, RAMP , DC, NOIS, or ARB."
Example = ":SOURce:FUNCtion SQUare /*Sets the output waveform type to Square.*/ :SOURce:FUNCtion? /*The query returns SQU.*/ 276"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.25.3 :SOURce:FREQuency"]
Syntax = ":SOURce:FREQuency <freq> :SOURce:FREQuency?"
Description = "Sets or queries the frequency of basic waveforms."
Remarks = "• Sine: 2 mHz to 25 MHz • Square: 2 mHz to 15 MHz • Ramp: 2 mHz to 150 kHz • Arb: 2 mHz to 10 MHz • DC and Noise: no frequency parameter You can use :SOURce:FUNCtion to set or query the basic wave type."
"Return Format" = "The query returns the frequency in scientific notation, for example, 2.000000E+5."
Example = ":SOURce:FREQuency 1000 /*Sets the frequency of the basic waveform to 1 kHz.*/ :SOURce:FREQuency? /*The query returns 1.000000E+3.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.25.4 :SOURce:PHASe"]
Syntax = ":SOURce:PHASe <phase> :SOURce:PHASe?"
Description = "Sets or queries the starting phase of basic waveforms. 277"
Remarks = "N/A"
"Return Format" = "The query returns the starting phase in scientific notation. For example, the query might return 1.0000000000E+01, indicating that the starting phase is 10°."
Example = ":SOURce:PHASe 10 /*Sets the starting phase of basic waveforms to 10°.*/ :SOURce:PHASe? /*The query returns 1.0000000000E+01.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.25.5 :SOURce:FUNCtion:RAMP:SYMMetry"]
Syntax = ":SOURce:FUNCtion:RAMP:SYMMetry <symm> :SOURce:FUNCtion:RAMP:SYMMetry?"
Description = "Sets or queries the symmetry of Ramp."
Remarks = "This command is available only when the waveform function (:SOURce:FUNCtion) is set to Ramp. Symmetry is defined as the percentage of the amount of time Ramp wave is rising in the period. T t Symmetry=t/T*100% 278"
"Return Format" = "The query returns the symmetry in scientific notation. For example, the query might return 5.5000000000E+01, indicating that the Ramp symmetry is 55%."
Example = ":SOURce:FUNCtion:RAMP:SYMMetry 55 /*Sets the symmetry of Ramp to 55%.*/ :SOURce:FUNCtion:RAMP:SYMMetry? /*The query returns 5.5000000000E +01.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.25.6 :SOURce:FUNCtion:SQUare:DUYT"]
Syntax = ":SOURce:FUNCtion:SQUare:DUYT <percent> :SOURce:FUNCtion:SQUare:DUYT?"
Description = "Sets or queries the duty cycle of the square wave generated by the AFG function."
Remarks = "This command is valid only when the wave type is set to \"Square\". You can use :SOURce:FUNCtion to set or query the waveform type. Square duty cycle is the percentage of time that the square wave is at a high level over the period of the square wave."
"Return Format" = "The query returns the duty cycle in scientific notation."
Example = ":SOURce:FUNCtion:SQUare:DUYT 55 /*Sets the square duty cycle to 55%.*/ :SOURce:FUNCtion:SQUare:DUYT? /*The query returns 5.5000000000E +01.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.25.7 :SOURce:VOLTage:AMPLitude"]
Syntax = ":SOURce:VOLTage:AMPLitude <amp> :SOURce:VOLTage:AMPLitude 279"
Description = "Sets or queries the amplitude of basic waveforms. The default unit is V."
Remarks = "The amplitude range of basic waveforms is related to the frequency: • 2 mV to 10 V (frequency ≤ 10 MHz) • 2 mV to 5 V (frequency > 10 MHz) You can use :SOURce:FREQuency to set or query the frequency of the basic waveform."
"Return Format" = "The query returns the amplitude in scientific notation. The unit is V."
Example = ":SOURce:VOLTage:AMPLitude 1 /*Sets the amplitude to 1 V.*/ :SOURce:VOLTage:AMPLitude? /*The query returns 1.0000000000E+00.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.25.8 :SOURce:VOLTage:OFFSet"]
Syntax = ":SOURce:VOLTage:OFFSet <offset> :SOURce:VOLTage:OFFSet?"
Description = "Sets or queries the offset of basic waveforms. The default unit is V."
Remarks = "The offset range of basic waveforms is related to the amplitude: Offset range = ± (maximum amplitude that can be set - current amplitude)/2 For example, 280 • If the frequency of the current basic waveform is 5 MHz, the maximum amplitude that can be set is 10 V, and the set amplitude is 6 V, then the offset range is ±(10 V - 6 V)/2 = ±2 V. • If the frequency of the current basic waveform is 15 MHz, the maximum amplitude that can be set is 5 V, and the set amplitude is 3 V, then the offset range is ±(5 V - 3 V)/2 = ±1 V. You can use :SOURce:VOLTage:AMPLitude to set or query the amplitude of the basic waveform."
"Return Format" = "The query returns the offset in scientific notation. The unit is V."
Example = ":SOURce:VOLTage:OFFSet 0.2 /*Sets the waveform offset to 200 mV.*/ :SOURce:VOLTage:OFFSet? /*The query returns 2.0000000000E-01.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.25.9 :SOURce:MOD:STATe"]
Syntax = ":SOURce:MOD:STATe <bool> :SOURce:MOD:STATe?"
Description = "Enables or disables the modulation output; or queries the modulation output status."
Remarks = "N/A"
"Return Format" = "The query returns 1 or 0."
Example = ":SOURce:MOD:STATe /*Enables the modulation output*/ :SOURce:MOD:STATe? /*The query returns 1.*/ 281"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.25.10 :SOURce:MOD:TYPe"]
Syntax = ":SOURce:MOD:TYPe <type> :SOURce:MOD:TYPe?"
Description = "Sets or queries the modulation type."
Remarks = "• AM: amplitude modulation. The amplitude of the carrier waveform is varied by the voltage of the modulating waveform. • FM: frequency modulation. The frequency of the carrier waveform is varied by the voltage of the modulating waveform. • PM: phase modulation. The phase of the carrier waveform is varied by the voltage of the modulating waveform."
"Return Format" = "The query returns AM, FM, or PM."
Example = ":SOURce:MOD:TYPe AM /*Sets the modulation type to AM*/ :SOURce:MOD:TYPe? /*The query returns AM.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.25.11 :SOURce:MOD:AM:DEPTh"]
Syntax = ":SOURce:MOD:AM:DEPTh <depth> :SOURce:MOD:AM:DEPTh?"
Description = "Sets or queries the modulation depth of AM. 282"
Remarks = "Modulation depth is a percentage that represents the amplitude variation. • At 0% depth, the amplitude is one-half of the carrier's amplitude setting. • At 100% depth, the amplitude is identical to the carrier's amplitude setting. • At greater than 100% depth, envelop distortion will occur which must be avoided in actual circuits. The instrument will not exceed 2.5 Vpp on the output (into a 50 Ω load)."
"Return Format" = "The query returns the AM modulation depth in scientific notation. For example, the query might return 5.0000000000E+01, indicating that the modulation depth is 50%."
Example = ":SOURce:MOD:AM:DEPTh 50 /*Sets the modulation depth of AM to 50%.*/ :SOURce:MOD:AM:DEPTh? /*The query returns 5.0000000000E+01.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.25.12 :SOURce:MOD:AM:INTernal:FREQuency"]
Syntax = ":SOURce:MOD:AM:INTernal:FREQuency <freq> :SOURce:MOD:AM:INTernal:FREQuency?"
Description = "Sets or queries the modulation frequency of AM."
Remarks = "N/A 283"
"Return Format" = "The query returns the AM modulation frequency in scientific notation. For example, the query might return 1.5000000000E+02, indicating that the modulation frequency is 150 Hz."
Example = ":SOURce:MOD:AM:INTernal:FREQuency 150 /*Sets the modulation frequency of AM to 150 Hz.*/ :SOURce:MOD:AM:INTernal:FREQuency? /*The query returns 1.5000000000E +02.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.25.13 :SOURce:MOD:AM:INTernal:FUNCtion"]
Syntax = ":SOURce:MOD:AM:INTernal:FUNCtion <function> :SOURce:MOD:AM:INTernal:FUNCtion?"
Description = "Sets or queries the modulation waveform of AM."
Remarks = "• SINusoid: sine wave. • SQUare: square with 50% duty cycle. • TRIangle: triangle with 50% symmetry • UPRamp: UpRamp with 100% symmetry. • DNRamp: DnRamp with 0% symmetry. • NOISe: noise-white gaussian noise."
"Return Format" = "The query returns SIN, SQU, TRI, UPR, DNR, and NOIS."
Example = ":SOURce:MOD:AM:INTernal:FUNCtion SQUare /*Sets the modulation waveform of AM to Square.*/ :SOURce:MOD:AM:INTernal:FUNCtion? /*The query returns SQU.*/ 284"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.25.14 :SOURce:MOD:FM:DEViation"]
Syntax = ":SOURce:MOD:FM:DEViation <deviation> :SOURce:MOD:FM:DEViation?"
Description = "Sets or queries the frequency deviation of FM."
Remarks = "• Frequency deviation represents the peak variation in frequency of the modulated waveform from the carrier frequency. • The carrier frequency plus the deviation must be less than or equal to the selected carrier's maximum frequency plus 1 kHz. • The ranges of different carrier frequencies (:SOURce:FREQuency) vary in different modulation modes."
"Return Format" = "The query returns the frequency deviation in scientific notation. For example, the query might return 1.0000000000E+02, indicating that the frequency deviation is 100 Hz."
Example = ":SOURce:MOD:FM:DEViation 100 /*Sets the frequency deviation of FM to 100 Hz.*/ :SOURce:MOD:FM:DEViation? /*The query returns 1.0000000000E+02.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.25.15 :SOURce:MOD:FM:INTernal:FREQuency"]
Syntax = ":SOURce:MOD:FM:INTernal:FREQuency <freq> :SOURce:MOD:FM:INTernal:FREQuency?"
Description = "Sets or queries the modulation frequency of FM. 285"
Remarks = "N/A"
"Return Format" = "The query returns the FM modulation frequency in scientific notation. For example, the query might return 1.5000000000E+02, indicating that the modulation frequency is 150 Hz."
Example = ":SOURce:MOD:FM:INTernal:FREQuency 150 /*Sets the modulation frequency of FM to 150 Hz.*/ :SOURce:MOD:FM:INTernal:FREQuency? /*The query returns 1.5000000000E +02.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.25.16 :SOURce:MOD:FM:INTernal:FUNCtion"]
Syntax = ":SOURce:MOD:FM:INTernal:FUNCtion <function> :SOURce:MOD:FM:INTernal:FUNCtion?"
Description = "Sets or queries the modulation waveform of FM."
Remarks = "• SINusoid: sine wave. • SQUare: square with 50% duty cycle. • TRIangle: triangle with 50% symmetry • UPRamp: UpRamp with 100% symmetry. • DNRamp: DnRamp with 0% symmetry. • NOISe: noise-white gaussian noise. 286"
"Return Format" = "The query returns SIN, SQU, TRI, UPR, DNR, and NOIS."
Example = ":SOURce:MOD:FM:INTernal:FUNCtion SQUare /*Sets the modulation waveform of FM to Square.*/ :SOURce:MOD:FM:INTernal:FUNCtion? /*The query returns SQU.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.25.17 :SOURce:MOD:PM:DEViation"]
Syntax = ":SOURce:MOD:PM:DEViation <deviation> :SOURce:MOD:PM:DEViation?"
Description = "Sets or queries the phase deviation of PM."
Remarks = "Phase deviation represents the peak variation in phase of the modulated waveform from the carrier waveform."
"Return Format" = "The query returns the PM phase deviation in scientific notation. For example, the query might return 5.0000000000E+01, indicating that the phase deviation is 50°."
Example = ":SOURce:MOD:PM:DEViation 50 /*Sets the phase deviation of PM to 50°.*/ :SOURce:MOD:PM:DEViation? /*The query returns 5.0000000000E+01.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.25.18 :SOURce:MOD:PM:INTernal:FREQuency"]
Syntax = ":SOURce:MOD:PM:INTernal:FREQuency <freq> :SOURce:MOD:PM:INTernal:FREQuency?"
Description = "Sets or queries the modulation frequency of PM. 287"
Remarks = "N/A"
"Return Format" = "The query returns the PM modulation frequency in scientific notation. For example, the query might return 1.5000000000E+02, indicating that the modulation frequency is 150 Hz."
Example = ":SOURce:MOD:PM:INTernal:FREQuency 150 /*Sets the modulation frequency of PM to 150 Hz.*/ :SOURce:MOD:PM:INTernal:FREQuency? /*The query returns 1.5000000000E +02.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.25.19 :SOURce:MOD:PM:INTernal:FUNCtion"]
Syntax = ":SOURce:MOD:PM:INTernal:FUNCtion <function> :SOURce:MOD:PM:INTernal:FUNCtion?"
Description = "Sets or queries the modulation waveform of PM."
Remarks = "• SINusoid: sine wave. • SQUare: square with 50% duty cycle. • TRIangle: triangle with 50% symmetry • UPRamp: UpRamp with 100% symmetry. • DNRamp: DnRamp with 0% symmetry. • NOISe: noise-white gaussian noise. 288"
"Return Format" = "The query returns SIN, SQU, TRI, UPR, DNR, and NOIS."
Example = ":SOURce:MOD:PM:INTernal:FUNCtion SQUare /*Sets the modulation waveform of PM to Square.*/ :SOURce:MOD:PM:INTernal:FUNCtion? /*The query returns SQU.*/ 3.26 :TIMebase Commands :TIMebase commands are used to set the horizontal system. For example, you can enable the Zoom mode or set the horizontal time base mode. Horizontal Time Base Mode • YT Mode: By default, this series oscilloscope uses the YT mode for waveform display window. In YT mode, Y-axis indicates the Voltage and X-axis indicates the Time. • XY Mode: In XY mode, both the X-axis and Y-axis indicate voltage. The XY mode converts the oscilloscope from a \"Voltage-Time\" display to a \"Voltage-Voltage\" display using two input channels. The XY mode can be used to measure the phase deviation occurred when the signal under test passes through a circuit network. • Roll Mode: The roll mode causes the waveform to move across the screen from right to left. It allows you to view the acquired data without waiting for a complete acquisition. The Roll mode is automatically enabled when the horizontal time base is set to 50 ms/div or slower. TIP - If the Zoom mode is currently turned on, enabling the roll mode automatically turns off the Zoom mode. - The following functions are not available when the roll mode is enabled: To Adjust the Horizontal Position (available when the oscilloscope run state is STOP), Zoom Mode (Delayed Sweep), Triggering the Oscilloscope, Protocol Decoding, Pass/Fail Test, Waveform Recording and Playing, Persistence Time, XY Mode, and Average. 289"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.25.1 :SOURce:OUTPut:STATe".Parameter]
Name = "<bool>"
Type = "Bool"
Default = "0|OFF"
Range = "{{1|ON}|{0|OFF}}"

["3.25.2 :SOURce:FUNCtion".Parameter]
Name = "<wave>"
Type = "Discrete"
Default = "SINusoid"
Range = "{SINusoid|SQUare|RAMP|DC| NOISe|ARB}"

["3.25.3 :SOURce:FREQuency".Parameter]
Name = "<freq>"
Type = "Real"
Default = "kHz"
Range = "Refer to Remarks 1"

["3.25.4 :SOURce:PHASe".Parameter]
Name = "<phase>"
Type = "Real"
Default = "0°"
Range = "0° to 360°"

["3.25.5 :SOURce:FUNCtion:RAMP:SYMMetry".Parameter]
Name = "<symm>"
Type = "Real"
Default = "50%"
Range = "0% to 100%"

["3.25.6 :SOURce:FUNCtion:SQUare:DUYT".Parameter]
Name = "<percent>"
Type = "Real"
Default = "50"
Range = "0 to 100"

["3.25.7 :SOURce:VOLTage:AMPLitude".Parameter]
Name = "<amp>"
Type = "Real"
Default = "V"
Range = "Refer to Remarks 6"

["3.25.8 :SOURce:VOLTage:OFFSet".Parameter]
Name = "<offset>"
Type = "Real"
Default = "V"
Range = "Refer to Remarks 0"

["3.25.9 :SOURce:MOD:STATe".Parameter]
Name = "<bool>"
Type = "Bool"
Default = "0|OFF"
Range = "{{1|ON}|{0|OFF}}"

["3.25.10 :SOURce:MOD:TYPe".Parameter]
Name = "<type>"
Type = "Discrete"
Default = "AM"
Range = "{AM|FM|PM}"

["3.25.11 :SOURce:MOD:AM:DEPTh".Parameter]
Name = "<depth>"
Type = "Real"
Default = "100%"
Range = "0% to 120%"

["3.25.12 :SOURce:MOD:AM:INTernal:FREQuency".Parameter]
Name = "<freq>"
Type = "Real"
Default = "Hz"
Range = "2 mHz to 1 MHz 100"

["3.25.13 :SOURce:MOD:AM:INTernal:FUNCtion".Parameter]
Name = "<function>"
Type = "Discrete"
Default = "SINusoid"
Range = "{SINusoid|SQUare|TRIangle| UPRamp|DNRamp|NOISe}"

["3.25.14 :SOURce:MOD:FM:DEViation".Parameter]
Name = "<deviation>"
Type = "Real"
Default = "kHz"
Range = "2 mHz to the current carrier frequency 1"

["3.25.15 :SOURce:MOD:FM:INTernal:FREQuency".Parameter]
Name = "<freq>"
Type = "Real"
Default = "Hz"
Range = "2 mHz to 1 MHz 100"

["3.25.16 :SOURce:MOD:FM:INTernal:FUNCtion".Parameter]
Name = "<function>"
Type = "Discrete"
Default = "SINusoid"
Range = "{SINusoid|SQUare|TRIangle| UPRamp|DNRamp|NOISe}"

["3.25.17 :SOURce:MOD:PM:DEViation".Parameter]
Name = "<deviation>"
Type = "Real"
Default = "90°"
Range = "0° to 360°"

["3.25.18 :SOURce:MOD:PM:INTernal:FREQuency".Parameter]
Name = "<freq>"
Type = "Real"
Default = "Hz"
Range = "2 mHz to 1 MHz 100"

["3.25.19 :SOURce:MOD:PM:INTernal:FUNCtion".Parameter]
Name = "<function>"
Type = "Discrete"
Default = "SINusoid"
Range = "{SINusoid|SQUare|TRIangle| UPRamp|DNRamp|NOISe}"
