# 3.26 :TIMebase Commands

["3.26.1 :TIMebase:DELay:ENABle"]
Syntax = ":TIMebase:DELay:ENABle <bool> :TIMebase:DELay:ENABle?"
Description = "Turns on or off the delayed sweep; or queries the on/off status of the delayed sweep."
Remarks = "Delayed sweep enlarges a portion of the waveform horizontally."
"Return Format" = "The query returns 1 or 0."
Example = ":TIMebase:DELay:ENABle ON    /*Enables the delayed sweep.*/ :TIMebase:DELay:ENABle?      /*Returns 1.*/"
Class = "Timebase.Delay"
Function = "enable"
Command = ":TIMebase:DELay:ENABle"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{OFF|ON}"
Is_Query = "Yes"

["3.26.2 :TIMebase:DELay:OFFSet"]
Syntax = ":TIMebase:DELay:OFFSet <offset> :TIMebase:DELay:OFFSet?"
Description = "Sets or queries the offset of the delayed time base."
Remarks = "DelayRange depends on the main scale, offset, and the selected delay scale."
"Return Format" = "The query returns the offset in scientific notation."
Example = ":TIMebase:DELay:OFFSet 0.000002   /*Sets delayed offset to 2 μs.*/ :TIMebase:DELay:OFFSet? /*Might return 2.000000E-6.*/"
Class = "Timebase.Delay"
Function = "offset"
Command = ":TIMebase:DELay:OFFSet"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "float"
Is_Query = "Yes"

["3.26.3 :TIMebase:DELay:SCALe"]
Syntax = ":TIMebase:DELay:SCALe <scale> :TIMebase:DELay:SCALe?"
Description = "Sets or queries the scale of the delayed time base (s/div)."
Remarks = "Maximum scale equals current main time base scale. Only certain discrete steps (1-2-5) are available."
"Return Format" = "The query returns the delay scale in scientific notation."
Example = ":TIMebase:DELay:SCALe 0.00000005 /*Sets delay scale to 50 ns/div.*/ :TIMebase:DELay:SCALe? /*Might return 5.000000E-8.*/"
Class = "Timebase.Delay"
Function = "scale"
Command = ":TIMebase:DELay:SCALe"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "float"
Is_Query = "Yes"

["3.26.4 :TIMebase[:MAIN][:OFFSet]"]
Syntax = ":TIMebase[:MAIN][:OFFSet] <offset> :TIMebase[:MAIN][:OFFSet]?"
Description = "Sets or queries the offset of the main time base (s)."
Remarks = "Offset range depends on the run state and the main time base scale."
"Return Format" = "The query returns the main time base offset in scientific notation."
Example = ":TIMebase:MAIN:OFFSet 0.0002 /*Sets offset to 200 μs.*/ :TIMebase:MAIN:OFFSet? /*Might return 2.000000E-4.*/"
Class = "Timebase.Main"
Function = "offset"
Command = ":TIMebase:MAIN:OFFSet"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "float"
Is_Query = "Yes"

["3.26.5 :TIMebase[:MAIN]:SCALe"]
Syntax = ":TIMebase[:MAIN]:SCALe <scale> :TIMebase[:MAIN]:SCALe?"
Description = "Sets or queries the main time base scale."
Remarks = "The valid range depends on the bandwidth and the horizontal mode."
"Return Format" = "The query returns the main time base scale in scientific notation."
Example = ":TIMebase:MAIN:SCALe 0.0002 /*Sets scale to 200 μs/div.*/ :TIMebase:MAIN:SCALe? /*Might return 2.000000E-4.*/"
Class = "Timebase.Main"
Function = "scale"
Command = ":TIMebase:MAIN:SCALe"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "float"
Is_Query = "Yes"

["3.26.6 :TIMebase:MODE"]
Syntax = ":TIMebase:MODE <mode> :TIMebase:MODE?"
Description = "Sets or queries the horizontal time base mode."
Remarks = "• MAIN => YT mode. • XY => XY mode. • ROLL => Roll mode."
"Return Format" = "The query returns MAIN or ROLL."
Example = ":TIMebase:MODE ROLL /*Sets time base mode to ROLL.*/ :TIMebase:MODE? /*Might return ROLL.*/"
Class = "Timebase"
Function = "mode"
Command = ":TIMebase:MODE"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{MAIN|XY|ROLL}"
Is_Query = "Yes"

["3.26.7 :TIMebase:HREFerence:MODE"]
Syntax = ":TIMebase:HREFerence:MODE <href> :TIMebase:HREFerence:MODE?"
Description = "Sets or queries the horizontal reference mode."
Remarks = "CENTer, LB, RB, TRIG, or USER."
"Return Format" = "The query returns CENT, LB, RB, TRIG, or USER."
Example = ":TIMebase:HREFerence:MODE TRIG /*Sets reference mode to TRIG.*/ :TIMebase:HREFerence:MODE? /*Might return TRIG.*/"
Class = "Timebase.HReference"
Function = "mode"
Command = ":TIMebase:HREFerence:MODE"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{CENTer|LB|RB|TRIG|USER}"
Is_Query = "Yes"

["3.26.8 :TIMebase:HREFerence:POSition"]
Syntax = ":TIMebase:HREFerence:POSition <pos> :TIMebase:HREFerence:POSition?"
Description = "Sets or queries the user-defined reference position for horizontal scaling."
Remarks = "N/A"
"Return Format" = "Returns an integer from -500 to 500."
Example = ":TIMebase:HREFerence:POSition 60 /*Sets the reference position to 60.*/ :TIMebase:HREFerence:POSition? /*Might return 60.*/"
Class = "Timebase.HReference"
Function = "position"
Command = ":TIMebase:HREFerence:POSition"
Input_Min = "-500"
Input_Max = "500"
Input_Values = "integer"
Is_Query = "Yes"

["3.26.9 :TIMebase:VERNier"]
Syntax = ":TIMebase:VERNier <bool> :TIMebase:VERNier?"
Description = "Enables or disables the fine adjustment of the horizontal scale; or queries its status."
Remarks = "N/A"
"Return Format" = "The query returns 1 or 0."
Example = ":TIMebase:VERNier ON /*Fine adjustment ON.*/ :TIMebase:VERNier? /*Might return 1.*/"
Class = "Timebase"
Function = "vernier"
Command = ":TIMebase:VERNier"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{OFF|ON}"
Is_Query = "Yes"

["3.26.10 :TIMebase:HOTKeys"]
Syntax = ":TIMebase:HOTKeys <action>"
Description = "Sets the running status (STOP, RUN, or SINGle)."
Remarks = "N/A"
"Return Format" = "N/A"
Example = ":TIMebase:HOTKeys RUN /*Sets operating status to RUN.*/"
Class = "Timebase"
Function = "hotkeys"
Command = ":TIMebase:HOTKeys"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{STOP|RUN|SINGle}"
Is_Query = "No"

["3.26.11 :TIMebase:ROLL"]
Syntax = ":TIMebase:ROLL <value> :TIMebase:ROLL?"
Description = "Sets or queries the status of the ROLL mode."
Remarks = "• 0 = disabled. • 1 = enabled (auto ROLL if time base ≥ 50 ms)."
"Return Format" = "The query returns 0 or 1."
Example = ":TIMebase:ROLL 0 /*Disables the ROLL mode.*/ :TIMebase:ROLL? /*Might return 0.*/"
Class = "Timebase"
Function = "roll"
Command = ":TIMebase:ROLL"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{0|1}"
Is_Query = "Yes"

["3.26.12 :TIMebase:XY:ENABle"]
Syntax = ":TIMebase:XY:ENABle <bool> :TIMebase:XY:ENABle?"
Description = "Enables or disables the XY mode; or queries the on/off status of XY mode."
Remarks = "N/A"
"Return Format" = "The query returns 0 or 1."
Example = ":TIMebase:XY:ENABle OFF /*Disables XY mode.*/ :TIMebase:XY:ENABle? /*Might return 0.*/"
Class = "Timebase.XY"
Function = "enable"
Command = ":TIMebase:XY:ENABle"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{OFF|ON}"
Is_Query = "Yes"

["3.26.13 :TIMebase:XY:X"]
Syntax = ":TIMebase:XY:X <s> :TIMebase:XY:X?"
Description = "Sets or queries the channel source for the X coordinate when in XY mode."
Remarks = "N/A"
"Return Format" = "Returns CHAN1, CHAN2, CHAN3, or CHAN4."
Example = ":TIMebase:XY:X CHANnel3 /*Sets X source to CHAN3.*/ :TIMebase:XY:X? /*Might return CHAN3.*/"
Class = "Timebase.XY"
Function = "x_source"
Command = ":TIMebase:XY:X"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{CHANnel1|CHANnel2|CHANnel3|CHANnel4}"
Is_Query = "Yes"

["3.26.14 :TIMebase:XY:Y"]
Syntax = ":TIMebase:XY:Y <s> :TIMebase:XY:Y?"
Description = "Sets or queries the channel source for the Y coordinate when in XY mode."
Remarks = "N/A"
"Return Format" = "Returns CHAN1, CHAN2, CHAN3, or CHAN4."
Example = ":TIMebase:XY:Y CHANnel3 /*Sets Y source to CHAN3.*/ :TIMebase:XY:Y? /*Might return CHAN3.*/"
Class = "Timebase.XY"
Function = "y_source"
Command = ":TIMebase:XY:Y"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{CHANnel1|CHANnel2|CHANnel3|CHANnel4}"
Is_Query = "Yes"

["3.26.15 :TIMebase:XY:Z"]
Syntax = ":TIMebase:XY:Z <s> :TIMebase:XY:Z?"
Description = "Sets or queries Source Z in XY mode."
Remarks = "N/A"
"Return Format" = "Returns NONE, CHAN1, CHAN2, CHAN3, or CHAN4."
Example = ":TIMebase:XY:Z CHANnel3 /*Sets Z source to CHAN3.*/ :TIMebase:XY:Z? /*Might return CHAN3.*/"
Class = "Timebase.XY"
Function = "z_source"
Command = ":TIMebase:XY:Z"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{NONE|CHANnel1|CHANnel2|CHANnel3|CHANnel4}"
Is_Query = "Yes"

["3.26.16 :TIMebase:XY:GRID"]
Syntax = ":TIMebase:XY:GRID <grid> :TIMebase:XY:GRID?"
Description = "Sets or queries the grid type of the XY display."
Remarks = "• FULL: background grid + coordinates on. • HALF: no grid, but coordinates on. • NONE: no grid, no coordinates."
"Return Format" = "Returns FULL, HALF, or NONE."
Example = ":TIMebase:XY:GRID NONE /*Turns off both grid and coordinates.*/ :TIMebase:XY:GRID? /*Might return NONE.*/"
Class = "Timebase.XY"
Function = "grid"
Command = ":TIMebase:XY:GRID"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{FULL|HALF|NONE}"
Is_Query = "Yes"

["3.26.1 :TIMebase:DELay:ENABle".Parameter]
Name = "<bool>"
Type = "Bool"
Default = "0|OFF"
Range = "{{1|ON}|{0|OFF}}"

["3.26.2 :TIMebase:DELay:OFFSet".Parameter]
Name = "<offset>"
Type = "Real"
Default = "0"
Range = "-(LeftTime - DelayRange/2) to (RightTime - DelayRange/2)"

["3.26.3 :TIMebase:DELay:SCALe".Parameter]
Name = "<scale>"
Type = "Real"
Default = "-"
Range = "Refer to Remarks"

["3.26.4 :TIMebase[:MAIN][:OFFSet]".Parameter]
Name = "<offset>"
Type = "Real"
Default = "0"
Range = "Refer to Remarks"

["3.26.5 :TIMebase[:MAIN]:SCALe".Parameter]
Name = "<scale>"
Type = "Real"
Default = "5ns/div"
Range = "Refer to Remarks"

["3.26.6 :TIMebase:MODE".Parameter]
Name = "<mode>"
Type = "Discrete"
Default = "MAIN"
Range = "{MAIN|XY|ROLL}"

["3.26.7 :TIMebase:HREFerence:MODE".Parameter]
Name = "<href>"
Type = "Discrete"
Default = "CENTer"
Range = "{CENTer|LB|RB|TRIG|USER}"

["3.26.8 :TIMebase:HREFerence:POSition".Parameter]
Name = "<pos>"
Type = "Integer"
Default = "0"
Range = "-500 to 500"

["3.26.9 :TIMebase:VERNier".Parameter]
Name = "<bool>"
Type = "Bool"
Default = "0|OFF"
Range = "{{1|ON}|{0|OFF}}"

["3.26.10 :TIMebase:HOTKeys".Parameter]
Name = "<action>"
Type = "Discrete"
Default = "-"
Range = "{STOP|RUN|SINGle}"

["3.26.11 :TIMebase:ROLL".Parameter]
Name = "<value>"
Type = "Integer"
Default = "1"
Range = "{0|1}"

["3.26.12 :TIMebase:XY:ENABle".Parameter]
Name = "<bool>"
Type = "Bool"
Default = "0|OFF"
Range = "{{1|ON}|{0|OFF}}"

["3.26.13 :TIMebase:XY:X".Parameter]
Name = "<s>"
Type = "Discrete"
Default = "CHANnel1"
Range = "{CHANnel1|CHANnel2| CHANnel3|CHANnel4}"

["3.26.14 :TIMebase:XY:Y".Parameter]
Name = "<s>"
Type = "Discrete"
Default = "CHANnel2"
Range = "{CHANnel1|CHANnel2| CHANnel3|CHANnel4}"

["3.26.15 :TIMebase:XY:Z".Parameter]
Name = "<s>"
Type = "Discrete"
Default = "-"
Range = "{NONE|CHANnel1|CHANnel2| CHANnel3|CHANnel4}"

["3.26.16 :TIMebase:XY:GRID".Parameter]
Name = "<grid>"
Type = "Discrete"
Default = "FULL"
Range = "{FULL|HALF|NONE}"
