# 3.28 :WAVeform Commands
["3.28.1 :WAVeform:SOURce"]
Syntax = ":WAVeform:SOURce <source> :WAVeform:SOURce?"
Description = "Sets or queries the source channel of waveform data reading."
Remarks = "When the channel source is set to MATH1~MATH4, :WAVeform:MODE can only select the NORMal mode. D0~D15 are only available for the DHO900 series."
"Return Format" = "The query returns D0, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14, D15, CHAN1, CHAN2, CHAN3, CHAN4, MATH1, MATH2, MATH3, or MATH4."
Example = ":WAVeform:SOURce CHANnel2    /*Sets the channel source to CHANnel2.*/ :WAVeform:SOURce?             /*The query returns CHAN2.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.28.2 :WAVeform:MODE"]
Syntax = ":WAVeform:MODE <mode> :WAVeform:MODE?"
Description = "Sets or queries the mode of the :WAVeform:DATA? command in reading data."
Remarks = "• NORMal: reads the waveform data currently displayed on the screen. • MAXimum: reads the waveform data displayed on the screen when the oscilloscope is in the Run state; reads the waveform data from the internal memory when the oscilloscope is in the Stop state. • RAW: reads the waveform data from the internal memory. Note: The data in the internal memory can only be read when the oscilloscope is in the Stop state. You are not allowed to operate the instrument when it is reading data. • When the channel source is set to MATH, only the NORMal mode is valid."
"Return Format" = "The query returns NORM, MAX, or RAW."
Example = ":WAVeform:MODE RAW  /*Sets the reading mode of waveform data to RAW.*/ :WAVeform:MODE?      /*The query returns RAW.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.28.3 :WAVeform:FORMat"]
Syntax = ":WAVeform:FORMat <format> :WAVeform:FORMat?"
Description = "Sets or queries the return format of the waveform data."
Remarks = "• WORD: Each waveform point occupies two bytes (16 bits). • BYTE: Each waveform point occupies one byte (8 bits). • ASCii: The query returns the actual voltage value of each waveform point in scientific notation; and the voltage values are separated by commas."
"Return Format" = "The query returns WORD, BYTE, or ASC."
Example = ":WAVeform:FORMat WORD   /*Sets the returned format of waveform data to WORD.*/ :WAVeform:FORMat?        /*The query returns WORD.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.28.4 :WAVeform:POINts"]
Syntax = ":WAVeform:POINts <point> :WAVeform:POINts?"
Description = "Sets or queries the number of the waveform points to be read in the current mode."
Remarks = "The range of <point> is related to the current reading mode of the waveform data. You can send the :WAVeform:MODE command to set or query the reading mode of the waveform data. • NORMal: 1 to 1,000 • RAW: 1 to the current maximum memory depth • MAXimum: In RUN state: 1 to the number of effective points on the current screen; In STOP state: 1 to the number of effective points in the current memory"
"Return Format" = "The query returns the number of waveform points in integer."
Example = ":WAVeform:POINts 100   /*Sets the number of waveform points to be read to 100.*/ :WAVeform:POINts?   /*The query returns 100.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.28.5 :WAVeform:DATA?"]
Syntax = ":WAVeform:DATA?"
Description = "Reads the waveform data."
Remarks = "Procedures of reading the waveform data from the screen: :WAV:SOUR CHAN1    /*Sets the channel source to CHANnel1.*/ :WAV:MODE NORMal   /*Sets the waveform reading mode to NORMal.*/ :WAV:FORM BYTE   /*Sets the return format of the waveform data to BYTE.*/ :WAV:DATA?    /*Reads the waveform data on the screen.*/ Procedures of reading the waveform data from the internal memory: :STOP    /*Sets the instrument to STOP state (you can only read the waveform data from the internal memory when the oscilloscope is in STOP state).*/ :WAV:SOUR CHAN1   /*Sets the channel source to CHANnel1.*/ :WAV:MODE RAW   /*Sets the waveform reading mode to RAW.*/ :WAV:FORM BYTE   /*Sets the return format of the waveform data to BYTE.*/ :WAV:STAR 1     /*Sets the start point of waveform data reading to the first waveform point.*/ :WAVeform:STOP 120000   /*Sets the stop point of waveform data reading to the 120,000th waveform point (last point).*/"
"Return Format" = "The return format is related to the return format of the currently selected waveform data (:WAVeform:FORMat). For detailed operations, refer to descriptions in Waveform Data Reading."
Example = ""
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.28.6 :WAVeform:XINCrement?"]
Syntax = ":WAVeform:XINCrement?"
Description = "Queries the time interval between two neighboring points of the currently selected channel source in the X direction."
Remarks = "The returned value is related to the current data reading mode: • In NORMal mode, XINCrement = TimeScale/100. • In RAW mode, XINCrement = 1/SampleRate. • In MAX mode, XINCrement = TimeScale/100 when the oscilloscope is in the Run state; XINCrement = 1/SampleRate when the oscilloscope is in the Stop state. The unit is related to the current channel source:"
"Return Format" = "The query returns the time difference in scientific notation."
Example = "N/A"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.28.7 :WAVeform:XORigin?"]
Syntax = ":WAVeform:XORigin?"
Description = "Queries the start time of the waveform data of the currently selected channel source in the X direction."
Remarks = "The returned value is related to the current data reading mode: • In NORMal mode, the query returns the start time of the waveform data displayed on the screen. • In RAW mode, the query returns the start time of the waveform data in the internal memory. • In MAX mode, the query returns the start time of the waveform data displayed on the screen when the instrument is in the RUN state; the query returns the start time of the waveform data in the internal memory when the instrument is in the Stop state. The unit is related to the current channel source."
"Return Format" = "The query returns the time value in scientific notation."
Example = "N/A"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.28.8 :WAVeform:XREFerence?"]
Syntax = ":WAVeform:XREFerence?"
Description = "Queries the reference time of the waveform points of the currently selected channel source in the X direction."
Remarks = "N/A"
"Return Format" = "The query returns 0 (namely the first waveform point on the screen or in the internal memory)."
Example = "N/A"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.28.9 :WAVeform:YINCrement?"]
Syntax = ":WAVeform:YINCrement?"
Description = "Queries the unit voltage value of the current source channel Y in the Y direction."
Remarks = "The returned value is related to the current data reading mode: • In NORMal mode, YINCrement = VerticalScale/25. • In RAW mode, YINCrement and Verticalscale of the memory waveforms are related to the currently selected Verticalscale. • In MAX mode, YINCrement = VerticalScale/25 when the instrument is in the RUN state; YINCrement is related to the VerticalScale of the internal waveform and the currently selected VerticalScale when the instrument is in the Stop state."
"Return Format" = "The query returns the unit voltage value in scientific notation."
Example = "N/A"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.28.10 :WAVeform:YORigin?"]
Syntax = ":WAVeform:YORigin?"
Description = "Queries the vertical offset relative to the vertical reference position of the currently selected channel source in the Y direction."
Remarks = "The returned value is related to the current data reading mode: • In NORMal mode, YORigin = VerticalOffset/YINCrement. • In RAW mode, YORigin is related to the VerticalScale of the memory waveforms and the currently selected VerticalScale. • In MAX mode, YORigin = VerticalOffset/YINCrement when the instrument is in the RUN state; YORigin is related to the VerticalScale of the internal waveform and the currently selected VerticalScale when the instrument is in the Stop state."
"Return Format" = "The query returns an integer."
Example = "N/A"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.28.11 :WAVeform:YREFerence?"]
Syntax = ":WAVeform:YREFerence?"
Description = "Queries the vertical reference position of the currently selected channel source in the Y direction."
Remarks = "The value of YREFerence is related to the configuration of the :WAVeform:FORMat command. The reference position is different for different return formats of waveform data."
"Return Format" = "The query returns an integer."
Example = "N/A"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.28.12 :WAVeform:STARt"]
Syntax = ":WAVeform:STARt <sta> :WAVeform:STARt?"
Description = "Sets or queries the start position of waveform data reading."
Remarks = "When reading the waveform data from the internal memory, the actual settable ranges of the start point and stop point of a reading operation are related to the memory depth of the oscilloscope and the return format of the waveform data currently selected. • In Normal mode, the range is from 1 to 1,000. • In Max mode, when the oscilloscope is in RUN state, its range is from 1 to 1,000; when the oscilloscope is in STOP state, its range is from 1 to current maximum memory depth. • In Raw mode, the range is from 1 to the current maximum memory depth."
"Return Format" = "The query returns an integer."
Example = ":WAVeform:STARt 100   /*Sets the start point to 100.*/ :WAVeform:STARt?   /*The query returns 100.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.28.13 :WAVeform:STOP"]
Syntax = ":WAVeform:STOP <stop> :WAVeform:STOP?"
Description = "Sets or queries the stop position of waveform data reading."
Remarks = "When reading the waveform data in the internal memory, the actual settable ranges of the start point and stop point of a reading operation are related to the memory depth of the oscilloscope and the return format of the waveform data currently selected. • In Normal mode, the range is from 1 to 1,000. • In Max mode, when the oscilloscope is in RUN state, its range is from 1 to 1,000; when the oscilloscope is in STOP state, its range is from 1 to current maximum memory depth. • In Raw mode, the range is from 1 to the current maximum memory depth."
"Return Format" = "The query returns an integer."
Example = ":WAVeform:STOP 500   /*Sets the stop point to 500.*/ :WAVeform:STOP?   /*The query returns 500.*/"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.28.14 :WAVeform:PREamble?"]
Syntax = ":WAVeform:PREamble?"
Description = "Queries all the waveform parameters."
Remarks = "N/A"
"Return Format" = "The query returns 10 waveform parameters, separated by commas. <format>,<type>,<points>,<count>,<xincrement>,<xorigin>,<xreference>,<yincre ment>,<yorigin>,<yreference> Wherein, <format>: indicates 0 (BYTE), 1 (WORD), or 2 (ASC). <type>: indicates 0 (NORMal), 1 (MAXimum), or 2 (RAW). <points>: an integer ranging from 1 to 50,000,000. <count>: indicates the number of averages in the average sample mode. The value of <count> parameter is 1 in other modes. <xincrement>: indicates the time difference between two neighboring points in the X direction. <xorigin>: indicates the start time of the waveform data in the X direction. <xreference>: indicates the reference time of the waveform data in the X direction. <yincrement>: indicates the step value of the waveforms in the Y direction. <yorigin>: indicates the vertical offset relative to the \"Vertical Reference Position\" in the Y direction. <yreference>: indicates the vertical reference position in the Y direction."
Example = ":WAVeform:PREamble?/*The query returns 0,0,1000,1,1.000000E-8,-5.000000E-6,0.000000E-12,4.000000E-03,0,128. */"
Class = ""
Function = ""
Command = ""
Input_Min = ""
Input_Max = ""
Input_Values = ""
Is_Query = ""

["3.28.1 :WAVeform:SOURce".Parameter]
Name = "<source>"
Type = "Discrete"
Default = "CHANnel1"
Range = "{D0|D1|D2|D3|D4|D5|D6|D7|D8| D9|D10|D11|D12|D13|D14|D15| CHANnel1|CHANnel2| CHANnel3|CHANnel4|MATH1| MATH2|MATH3|MATH4}"

["3.28.2 :WAVeform:MODE".Parameter]
Name = "<mode>"
Type = "Discrete"
Default = "NORMal"
Range = "{NORMal|MAXimum|RAW}"

["3.28.3 :WAVeform:FORMat".Parameter]
Name = "<format>"
Type = "Discrete"
Default = "BYTE"
Range = "{WORD|BYTE|ASCii}"

["3.28.4 :WAVeform:POINts".Parameter]
Name = "<point>"
Type = "Integer"
Default = "-"
Range = "Refer to Remarks"

["3.28.5 :WAVeform:DATA?".Parameter]
Info = "N/A"

["3.28.6 :WAVeform:XINCrement?".Parameter]
Info = "N/A"

["3.28.7 :WAVeform:XORigin?".Parameter]
Info = "N/A"

["3.28.8 :WAVeform:XREFerence?".Parameter]
Info = "N/A"

["3.28.9 :WAVeform:YINCrement?".Parameter]
Info = "N/A"

["3.28.10 :WAVeform:YORigin?".Parameter]
Info = "N/A"

["3.28.11 :WAVeform:YREFerence?".Parameter]
Info = "N/A"

["3.28.12 :WAVeform:STARt".Parameter]
Name = "<sta>"
Type = "Integer"
Default = "1"
Range = "Refer to Remarks"

["3.28.13 :WAVeform:STOP".Parameter]
Name = "<stop>"
Type = "Integer"
Default = "1,000"
Range = "Refer to Remarks"

["3.28.14 :WAVeform:PREamble?".Parameter]
Info = "N/A"
