# 3.28 :WAVeform Commands

["3.28.1 :WAVeform:SOURce"]
Syntax = ":WAVeform:SOURce <source> :WAVeform:SOURce?"
Description = "Sets or queries the source channel of waveform data reading."
Remarks = "When set to MATHx, only NORMal mode is allowed. D0~D15 are available only on DHO900 series."
"Return Format" = "Returns D0, D1, ..., D15, CHAN1..CHAN4, MATH1..MATH4."
Example = ":WAVeform:SOURce CHANnel2 /*Sets the source to CHANnel2.*/ :WAVeform:SOURce? /*Might return CHAN2.*/"
Class = "Waveform"
Function = "source"
Command = ":WAVeform:SOURce"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{D0|D1|D2|D3|D4|D5|D6|D7|D8|D9|D10|D11|D12|D13|D14|D15|CHANnel1|CHANnel2|CHANnel3|CHANnel4|MATH1|MATH2|MATH3|MATH4}"
Is_Query = "Yes"

["3.28.2 :WAVeform:MODE"]
Syntax = ":WAVeform:MODE <mode> :WAVeform:MODE?"
Description = "Sets or queries the mode for :WAVeform:DATA? (data reading)."
Remarks = "• NORMal: read displayed data. • MAXimum: read displayed data if RUN, or memory data if STOP. • RAW: read memory data (only STOP)."
"Return Format" = "Returns NORM, MAX, or RAW."
Example = ":WAVeform:MODE RAW /*Sets reading mode to RAW.*/ :WAVeform:MODE? /*Might return RAW.*/"
Class = "Waveform"
Function = "mode"
Command = ":WAVeform:MODE"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{NORMal|MAXimum|RAW}"
Is_Query = "Yes"

["3.28.3 :WAVeform:FORMat"]
Syntax = ":WAVeform:FORMat <format> :WAVeform:FORMat?"
Description = "Sets or queries the return format of the waveform data."
Remarks = "WORD = 16-bit. BYTE = 8-bit. ASCii = returns voltage in scientific notation."
"Return Format" = "Returns WORD, BYTE, or ASC."
Example = ":WAVeform:FORMat WORD /*Sets data return format to WORD.*/ :WAVeform:FORMat? /*Might return WORD.*/"
Class = "Waveform"
Function = "format"
Command = ":WAVeform:FORMat"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "{WORD|BYTE|ASCii}"
Is_Query = "Yes"

["3.28.4 :WAVeform:POINts"]
Syntax = ":WAVeform:POINts <point> :WAVeform:POINts?"
Description = "Sets or queries the number of points to read in the current mode."
Remarks = "In NORMal mode: 1 to 1,000; RAW mode: up to current memory depth; MAX mode: depends on Run or Stop state."
"Return Format" = "Returns an integer."
Example = ":WAVeform:POINts 100 /*Sets read points to 100.*/ :WAVeform:POINts? /*Might return 100.*/"
Class = "Waveform"
Function = "points"
Command = ":WAVeform:POINts"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "Integer"
Is_Query = "Yes"

["3.28.5 :WAVeform:DATA?"]
Syntax = ":WAVeform:DATA?"
Description = "Reads the waveform data."
Remarks = "Use in combination with :WAV:MODE, :WAV:FORM, :WAV:STAR, and :WAV:STOP for data retrieval."
"Return Format" = "Depends on the currently selected :WAVeform:FORMat."
Example = "N/A"
Class = "Waveform"
Function = "data"
Command = ":WAVeform:DATA?"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "Yes"

["3.28.6 :WAVeform:XINCrement?"]
Syntax = ":WAVeform:XINCrement?"
Description = "Queries the time step between consecutive waveform points (X direction)."
Remarks = "Depends on the reading mode: e.g. normal => TimeScale/100, raw => 1/SampleRate, etc."
"Return Format" = "Returns time increment in scientific notation."
Example = "N/A"
Class = "Waveform"
Function = "x_increment"
Command = ":WAVeform:XINCrement?"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "Yes"

["3.28.7 :WAVeform:XORigin?"]
Syntax = ":WAVeform:XORigin?"
Description = "Queries the start time (X direction) of the current waveform data."
Remarks = "Depends on reading mode: normal => screen data, raw => memory data, etc."
"Return Format" = "Returns time in scientific notation."
Example = "N/A"
Class = "Waveform"
Function = "x_origin"
Command = ":WAVeform:XORigin?"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "Yes"

["3.28.8 :WAVeform:XREFerence?"]
Syntax = ":WAVeform:XREFerence?"
Description = "Queries the reference time index of the waveform data (X direction)."
Remarks = "Typically returns 0 for the first waveform point."
"Return Format" = "Returns an integer (often 0)."
Example = "N/A"
Class = "Waveform"
Function = "x_reference"
Command = ":WAVeform:XREFerence?"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "Yes"

["3.28.9 :WAVeform:YINCrement?"]
Syntax = ":WAVeform:YINCrement?"
Description = "Queries the voltage step per data point (Y direction)."
Remarks = "normal => VerticalScale/25; raw => depends on memory waveforms + current scale; etc."
"Return Format" = "Returns a voltage step in scientific notation."
Example = "N/A"
Class = "Waveform"
Function = "y_increment"
Command = ":WAVeform:YINCrement?"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "Yes"

["3.28.10 :WAVeform:YORigin?"]
Syntax = ":WAVeform:YORigin?"
Description = "Queries the vertical offset relative to the reference in the Y direction."
Remarks = "normal => VerticalOffset / YINCrement, etc."
"Return Format" = "Returns an integer."
Example = "N/A"
Class = "Waveform"
Function = "y_origin"
Command = ":WAVeform:YORigin?"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "Yes"

["3.28.11 :WAVeform:YREFerence?"]
Syntax = ":WAVeform:YREFerence?"
Description = "Queries the vertical reference position (Y direction)."
Remarks = "Depends on :WAVeform:FORMat."
"Return Format" = "Returns an integer."
Example = "N/A"
Class = "Waveform"
Function = "y_reference"
Command = ":WAVeform:YREFerence?"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "Yes"

["3.28.12 :WAVeform:STARt"]
Syntax = ":WAVeform:STARt <sta> :WAVeform:STARt?"
Description = "Sets or queries the start point for waveform data reading."
Remarks = "Range depends on mode (NORMal up to 1,000, RAW up to memory depth, etc.)."
"Return Format" = "Returns an integer."
Example = ":WAVeform:STARt 100 /*Sets the start point to 100.*/ :WAVeform:STARt? /*Returns 100.*/"
Class = "Waveform"
Function = "start"
Command = ":WAVeform:STARt"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "Integer"
Is_Query = "Yes"

["3.28.13 :WAVeform:STOP"]
Syntax = ":WAVeform:STOP <stop> :WAVeform:STOP?"
Description = "Sets or queries the stop point for waveform data reading."
Remarks = "Range depends on mode. E.g. NORMal => up to 1,000; RAW => up to memory depth."
"Return Format" = "Returns an integer."
Example = ":WAVeform:STOP 500 /*Sets the stop point to 500.*/ :WAVeform:STOP? /*Might return 500.*/"
Class = "Waveform"
Function = "stop"
Command = ":WAVeform:STOP"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "Integer"
Is_Query = "Yes"

["3.28.14 :WAVeform:PREamble?"]
Syntax = ":WAVeform:PREamble?"
Description = "Queries all waveform parameters at once."
Remarks = "Returns 10 parameters in the order: <format>,<type>,<points>,<count>,<xincrement>,<xorigin>,<xreference>,<yincrement>,<yorigin>,<yreference>"
"Return Format" = "A comma-separated list of 10 parameters."
Example = ":WAVeform:PREamble? /*Might return 0,0,1000,1,1.000000E-8,...*/"
Class = "Waveform"
Function = "preamble"
Command = ":WAVeform:PREamble?"
Input_Min = "N/A"
Input_Max = "N/A"
Input_Values = "N/A"
Is_Query = "Yes"

["3.28.1 :WAVeform:SOURce".Parameter]
Name = "<source>"
Type = "Discrete"
Default = "CHANnel1"
Range = "{D0|D1|D2|D3|D4|D5|D6|D7|D8| D9|D10|D11|D12|D13|D14|D15| CHANnel1|CHANnel2| CHANnel3|CHANnel4|MATH1| MATH2|MATH3|MATH4}"

["3.28.2 :WAVeform:MODE".Parameter]
Name = "<mode>"
Type = "Discrete"
Default = "NORMal"
Range = "{NORMal|MAXimum|RAW}"

["3.28.3 :WAVeform:FORMat".Parameter]
Name = "<format>"
Type = "Discrete"
Default = "BYTE"
Range = "{WORD|BYTE|ASCii}"

["3.28.4 :WAVeform:POINts".Parameter]
Name = "<point>"
Type = "Integer"
Default = "-"
Range = "Refer to Remarks"

["3.28.5 :WAVeform:DATA?".Parameter]
Info = "N/A"

["3.28.6 :WAVeform:XINCrement?".Parameter]
Info = "N/A"

["3.28.7 :WAVeform:XORigin?".Parameter]
Info = "N/A"

["3.28.8 :WAVeform:XREFerence?".Parameter]
Info = "N/A"

["3.28.9 :WAVeform:YINCrement?".Parameter]
Info = "N/A"

["3.28.10 :WAVeform:YORigin?".Parameter]
Info = "N/A"

["3.28.11 :WAVeform:YREFerence?".Parameter]
Info = "N/A"

["3.28.12 :WAVeform:STARt".Parameter]
Name = "<sta>"
Type = "Integer"
Default = "1"
Range = "Refer to Remarks"

["3.28.13 :WAVeform:STOP".Parameter]
Name = "<stop>"
Type = "Integer"
Default = "1,000"
Range = "Refer to Remarks"

["3.28.14 :WAVeform:PREamble?".Parameter]
Info = "N/A"
